/**
 * Example themed override objects for the autocomplete theme system.
 *
 * Each theme is a `ThemeOverrides` — either a flat record (same for both modes)
 * or `{ light, dark }` with per-mode overrides.
 */

import type { ThemeOverrides } from '../../packages/theme/src';

// Non-color overrides shared across light and dark for a given theme.
const modernShape = {
  'autocomplete-base-unit': '16',
  'autocomplete-font-weight-medium': '600',
  'autocomplete-icon-size': '22',
  'autocomplete-icon-stroke-width': '1.4',
  'autocomplete-transition-duration': '0.2s',
  'autocomplete-transition-timing-function': 'ease-out',
  'autocomplete-search-input-height': '48',
  'autocomplete-form-padding-left': '22',
  'autocomplete-form-padding-right': '14',
  'autocomplete-form-border-radius': '12',
  'autocomplete-form-focus-ring-width': '3',
  'autocomplete-panel-border-radius': '12',
  'autocomplete-panel-gap': '10',
  'autocomplete-panel-padding': '10',
  'autocomplete-item-icon-box-size': '34',
  'autocomplete-item-border-radius': '8',
  'autocomplete-item-min-height': '48',
  'autocomplete-item-padding': '6',
  'autocomplete-highlight-weight': '700',
  'autocomplete-header-font-size': '0.75em',
  'autocomplete-header-font-weight': '700',
  'autocomplete-detached-modal-max-width': '720',
  'autocomplete-detached-modal-border-radius': '16',
  'autocomplete-scrollbar-width': '4',
  'autocomplete-scrollbar-color-mix': '25%',
};

/** Purple accent, rounded corners, larger items. */
export const modern: ThemeOverrides = {
  light: {
    ...modernShape,
    'autocomplete-primary-color': '109, 40, 217',
    'autocomplete-text-color': '24, 24, 27',
    'autocomplete-background-color': '255, 255, 255',
    'autocomplete-border-color': '212, 212, 216',
    'autocomplete-overlay-color': '24, 24, 27',
    'autocomplete-overlay-color-alpha': '0.4',
    'autocomplete-search-icon-color': '109, 40, 217',
    'autocomplete-placeholder-color': '161, 161, 170',
    'autocomplete-clear-button-color': '161, 161, 170',
    'autocomplete-form-border-opacity': '0.6',
    'autocomplete-form-focus-ring-opacity': '0.2',
    'autocomplete-panel-shadow':
      '0 0 0 1px rgba(109,40,217,0.08), 0 12px 32px -8px rgba(0,0,0,0.15)',
    'autocomplete-panel-border-opacity': '0.15',
    'autocomplete-item-selected-opacity': '0.08',
    'autocomplete-item-icon-color': '161, 161, 170',
    'autocomplete-item-action-color': '109, 40, 217',
    'autocomplete-header-color': '109, 40, 217',
    'autocomplete-header-line-opacity': '0.2',
    'autocomplete-detached-modal-shadow':
      '0 0 0 1px rgba(109,40,217,0.1), 0 24px 48px -12px rgba(0,0,0,0.2)',
  },
  dark: {
    ...modernShape,
    'autocomplete-primary-color': '139, 92, 246',
    'autocomplete-text-color': '229, 231, 235',
    'autocomplete-background-color': '24, 24, 27',
    'autocomplete-border-color': '63, 63, 70',
    'autocomplete-overlay-color': '0, 0, 0',
    'autocomplete-overlay-color-alpha': '0.6',
    'autocomplete-search-icon-color': '139, 92, 246',
    'autocomplete-placeholder-color': '113, 113, 122',
    'autocomplete-clear-button-color': '161, 161, 170',
    'autocomplete-form-border-opacity': '0.4',
    'autocomplete-form-focus-ring-opacity': '0.35',
    'autocomplete-panel-shadow':
      '0 0 0 1px rgba(139,92,246,0.1), 0 12px 32px -8px rgba(0,0,0,0.5)',
    'autocomplete-panel-border-opacity': '0.15',
    'autocomplete-item-selected-opacity': '0.15',
    'autocomplete-item-icon-color': '161, 161, 170',
    'autocomplete-item-action-color': '139, 92, 246',
    'autocomplete-header-color': '139, 92, 246',
    'autocomplete-header-line-opacity': '0.2',
    'autocomplete-detached-modal-shadow':
      '0 0 0 1px rgba(139,92,246,0.15), 0 24px 48px -12px rgba(0,0,0,0.6)',
  },
};

const warmMinimalShape = {
  'autocomplete-base-unit': '15',
  'autocomplete-font-weight-medium': '500',
  'autocomplete-icon-size': '18',
  'autocomplete-icon-stroke-width': '1.5',
  'autocomplete-transition-duration': '0.2s',
  'autocomplete-search-input-height': '42',
  'autocomplete-form-padding-left': '14',
  'autocomplete-form-padding-right': '12',
  'autocomplete-form-border-radius': '8',
  'autocomplete-form-focus-ring-width': '2',
  'autocomplete-panel-border-radius': '8',
  'autocomplete-panel-gap': '6',
  'autocomplete-panel-padding': '6',
  'autocomplete-item-icon-box-size': '26',
  'autocomplete-item-border-radius': '6',
  'autocomplete-item-min-height': '36',
  'autocomplete-item-padding': '4',
  'autocomplete-item-gap': '8',
  'autocomplete-item-line-height': '1.3em',
  'autocomplete-header-font-size': '0.7em',
  'autocomplete-header-font-weight': '600',
  'autocomplete-detached-modal-max-width': '580',
  'autocomplete-detached-modal-border-radius': '12',
  'autocomplete-scrollbar-width': '3',
  'autocomplete-scrollbar-color-mix': '15%',
};

/** Aesop-inspired: warm neutrals, understated luxury, generous whitespace. */
export const warmMinimal: ThemeOverrides = {
  light: {
    ...warmMinimalShape,
    'autocomplete-primary-color': '163, 113, 71',
    'autocomplete-text-color': '58, 50, 43',
    'autocomplete-background-color': '250, 247, 243',
    'autocomplete-border-color': '210, 200, 188',
    'autocomplete-muted-color-alpha': '0.5',
    'autocomplete-search-icon-color': '163, 113, 71',
    'autocomplete-placeholder-color': '158, 148, 136',
    'autocomplete-clear-button-color': '158, 148, 136',
    'autocomplete-form-border-opacity': '0.4',
    'autocomplete-form-focus-ring-opacity': '0.15',
    'autocomplete-panel-shadow':
      '0 1px 3px rgba(58,50,43,0.06), 0 4px 12px rgba(58,50,43,0.04)',
    'autocomplete-panel-border-opacity': '0.2',
    'autocomplete-item-selected-opacity': '0.06',
    'autocomplete-item-icon-color': '158, 148, 136',
    'autocomplete-item-action-color': '163, 113, 71',
    'autocomplete-header-color': '163, 113, 71',
    'autocomplete-header-line-opacity': '0.15',
    'autocomplete-detached-form-border-opacity': '0.2',
  },
  dark: {
    ...warmMinimalShape,
    'autocomplete-primary-color': '205, 160, 120',
    'autocomplete-text-color': '230, 222, 214',
    'autocomplete-background-color': '40, 35, 30',
    'autocomplete-border-color': '75, 65, 55',
    'autocomplete-muted-color-alpha': '0.45',
    'autocomplete-search-icon-color': '205, 160, 120',
    'autocomplete-placeholder-color': '140, 130, 118',
    'autocomplete-clear-button-color': '140, 130, 118',
    'autocomplete-form-border-opacity': '0.35',
    'autocomplete-form-focus-ring-opacity': '0.2',
    'autocomplete-panel-shadow':
      '0 1px 3px rgba(0,0,0,0.15), 0 4px 12px rgba(0,0,0,0.1)',
    'autocomplete-panel-border-opacity': '0.2',
    'autocomplete-item-selected-opacity': '0.1',
    'autocomplete-item-icon-color': '140, 130, 118',
    'autocomplete-item-action-color': '205, 160, 120',
    'autocomplete-header-color': '205, 160, 120',
    'autocomplete-header-line-opacity': '0.2',
    'autocomplete-detached-form-border-opacity': '0.25',
  },
};

const boldBrandShape = {
  'autocomplete-base-unit': '16',
  'autocomplete-font-weight-medium': '600',
  'autocomplete-icon-size': '20',
  'autocomplete-icon-stroke-width': '2.2',
  'autocomplete-transition-duration': '0.12s',
  'autocomplete-transition-timing-function': 'ease-out',
  'autocomplete-search-input-height': '50',
  'autocomplete-form-padding-left': '20',
  'autocomplete-form-padding-right': '16',
  'autocomplete-form-border-radius': '0',
  'autocomplete-form-focus-ring-width': '3',
  'autocomplete-panel-border-radius': '0',
  'autocomplete-panel-gap': '8',
  'autocomplete-panel-padding': '8',
  'autocomplete-item-icon-box-size': '32',
  'autocomplete-item-border-radius': '0',
  'autocomplete-item-min-height': '44',
  'autocomplete-item-padding': '6',
  'autocomplete-item-gap': '10',
  'autocomplete-highlight-weight': '800',
  'autocomplete-header-font-size': '0.72em',
  'autocomplete-header-font-weight': '700',
  'autocomplete-detached-modal-max-width': '680',
  'autocomplete-detached-modal-border-radius': '0',
  'autocomplete-scrollbar-width': '6',
  'autocomplete-scrollbar-color-mix': '40%',
};

/** Nike / Supreme inspired: black & white, bold type, sharp edges, punchy accent. */
export const boldBrand: ThemeOverrides = {
  light: {
    ...boldBrandShape,
    'autocomplete-primary-color': '230, 30, 40',
    'autocomplete-text-color': '10, 10, 10',
    'autocomplete-background-color': '255, 255, 255',
    'autocomplete-border-color': '10, 10, 10',
    'autocomplete-overlay-color': '10, 10, 10',
    'autocomplete-overlay-color-alpha': '0.5',
    'autocomplete-search-icon-color': '10, 10, 10',
    'autocomplete-placeholder-color': '140, 140, 140',
    'autocomplete-clear-button-color': '100, 100, 100',
    'autocomplete-form-border-opacity': '1',
    'autocomplete-form-focus-ring-opacity': '0.3',
    'autocomplete-panel-shadow': '4px 4px 0 rgba(10,10,10,1)',
    'autocomplete-panel-border-opacity': '1',
    'autocomplete-item-selected-opacity': '0.08',
    'autocomplete-item-icon-color': '80, 80, 80',
    'autocomplete-item-action-color': '230, 30, 40',
    'autocomplete-header-color': '230, 30, 40',
    'autocomplete-header-line-opacity': '0.4',
    'autocomplete-detached-modal-shadow': '6px 6px 0 rgba(10,10,10,1)',
    'autocomplete-detached-form-border-opacity': '1',
  },
  dark: {
    ...boldBrandShape,
    'autocomplete-primary-color': '255, 60, 70',
    'autocomplete-text-color': '245, 245, 245',
    'autocomplete-background-color': '15, 15, 15',
    'autocomplete-border-color': '245, 245, 245',
    'autocomplete-overlay-color': '0, 0, 0',
    'autocomplete-overlay-color-alpha': '0.65',
    'autocomplete-search-icon-color': '245, 245, 245',
    'autocomplete-placeholder-color': '120, 120, 120',
    'autocomplete-clear-button-color': '160, 160, 160',
    'autocomplete-form-border-opacity': '1',
    'autocomplete-form-focus-ring-opacity': '0.4',
    'autocomplete-panel-shadow': '4px 4px 0 rgba(245,245,245,1)',
    'autocomplete-panel-border-opacity': '1',
    'autocomplete-item-selected-opacity': '0.12',
    'autocomplete-item-icon-color': '180, 180, 180',
    'autocomplete-item-action-color': '255, 60, 70',
    'autocomplete-header-color': '255, 60, 70',
    'autocomplete-header-line-opacity': '0.4',
    'autocomplete-detached-modal-shadow': '6px 6px 0 rgba(245,245,245,1)',
    'autocomplete-detached-form-border-opacity': '1',
  },
};

const softPastelShape = {
  'autocomplete-base-unit': '16',
  'autocomplete-font-weight-medium': '500',
  'autocomplete-icon-size': '20',
  'autocomplete-icon-stroke-width': '1.5',
  'autocomplete-transition-duration': '0.5s',
  'autocomplete-transition-timing-function': 'cubic-bezier(0.22, 1, 0.36, 1)',
  'autocomplete-search-input-height': '48',
  'autocomplete-form-padding-left': '30',
  'autocomplete-form-padding-right': '18',
  'autocomplete-form-border-radius': '16',
  'autocomplete-form-focus-ring-width': '3',
  'autocomplete-panel-max-height': '600',
  'autocomplete-panel-border-radius': '16',
  'autocomplete-panel-gap': '12',
  'autocomplete-panel-padding': '14',
  'autocomplete-item-icon-box-size': '36',
  'autocomplete-item-border-radius': '12',
  'autocomplete-item-min-height': '44',
  'autocomplete-item-padding': '8',
  'autocomplete-item-gap': '10',
  'autocomplete-item-line-height': '1.4em',
  'autocomplete-highlight-weight': '600',
  'autocomplete-header-font-size': '0.78em',
  'autocomplete-header-font-weight': '600',
  'autocomplete-detached-modal-max-width': '640',
  'autocomplete-detached-modal-max-height': '520',
  'autocomplete-detached-modal-border-radius': '20',
  'autocomplete-detached-modal-top': '5%',
  'autocomplete-scrollbar-width': '5',
  'autocomplete-scrollbar-color-mix': '30%',
};

/** Soft pastel theme with teal accent, very rounded corners, generous padding. */
export const softPastel: ThemeOverrides = {
  light: {
    ...softPastelShape,
    'autocomplete-primary-color': '20, 184, 166',
    'autocomplete-primary-color-alpha': '0.9',
    'autocomplete-text-color': '55, 65, 81',
    'autocomplete-background-color': '248, 250, 252',
    'autocomplete-border-color': '196, 210, 224',
    'autocomplete-overlay-color': '100, 116, 139',
    'autocomplete-overlay-color-alpha': '0.3',
    'autocomplete-search-icon-color': '20, 184, 166',
    'autocomplete-placeholder-color': '148, 163, 184',
    'autocomplete-clear-button-color': '148, 163, 184',
    'autocomplete-form-border-opacity': '0.5',
    'autocomplete-form-focus-ring-opacity': '0.25',
    'autocomplete-panel-shadow':
      '0 0 0 1px rgba(20,184,166,0.08), 0 8px 24px -4px rgba(100,116,139,0.12)',
    'autocomplete-panel-border-opacity': '0.25',
    'autocomplete-item-selected-opacity': '0.08',
    'autocomplete-item-icon-color': '148, 163, 184',
    'autocomplete-item-action-color': '20, 184, 166',
    'autocomplete-header-color': '20, 184, 166',
    'autocomplete-header-line-opacity': '0.2',
    'autocomplete-detached-modal-shadow':
      '0 0 0 1px rgba(20,184,166,0.1), 0 16px 40px -8px rgba(100,116,139,0.15)',
    'autocomplete-detached-form-border-opacity': '0.25',
  },
  dark: {
    ...softPastelShape,
    'autocomplete-primary-color': '45, 212, 191',
    'autocomplete-text-color': '203, 213, 225',
    'autocomplete-background-color': '30, 41, 59',
    'autocomplete-border-color': '51, 65, 85',
    'autocomplete-overlay-color': '15, 23, 42',
    'autocomplete-overlay-color-alpha': '0.5',
    'autocomplete-search-icon-color': '45, 212, 191',
    'autocomplete-placeholder-color': '100, 116, 139',
    'autocomplete-clear-button-color': '100, 116, 139',
    'autocomplete-form-border-opacity': '0.4',
    'autocomplete-form-focus-ring-opacity': '0.3',
    'autocomplete-panel-shadow':
      '0 0 0 1px rgba(45,212,191,0.1), 0 8px 24px -4px rgba(0,0,0,0.3)',
    'autocomplete-panel-border-opacity': '0.2',
    'autocomplete-item-selected-opacity': '0.12',
    'autocomplete-item-icon-color': '100, 116, 139',
    'autocomplete-item-action-color': '45, 212, 191',
    'autocomplete-header-color': '45, 212, 191',
    'autocomplete-header-line-opacity': '0.25',
    'autocomplete-detached-modal-shadow':
      '0 0 0 1px rgba(45,212,191,0.12), 0 16px 40px -8px rgba(0,0,0,0.4)',
    'autocomplete-detached-form-border-opacity': '0.3',
  },
};
