import type { ShadowLayer, ThemePreset } from '../../types';

function shadow(
  offsetX: number,
  offsetY: number,
  blur: number,
  spread: number,
  color: string,
  opacity: number
): ShadowLayer {
  return { offsetX, offsetY, blur, spread, color, opacity };
}

export const AUTOCOMPLETE_PRESETS: ThemePreset[] = [
  // Luxury/premium: violet accent, refined spacing, deep shadows, thin borders.
  {
    name: 'Default',
    overrides: {
      light: {
        'autocomplete-text-color': '24, 24, 27',
        'autocomplete-form-border-color': '212, 212, 216',
        'autocomplete-panel-border-color': '212, 212, 216',
        'autocomplete-detached-modal-border-color': '212, 212, 216',
        'autocomplete-detached-form-border-color': '212, 212, 216',
        'autocomplete-form-search-icon-color': '109, 40, 217',
        'autocomplete-form-placeholder-color': '161, 161, 170',
        'autocomplete-form-clear-button-color': '161, 161, 170',
        'autocomplete-header-color': '109, 40, 217',
        'autocomplete-item-icon-color': '161, 161, 170',
        'autocomplete-item-action-color': '109, 40, 217',
        'autocomplete-form-button-horizontal-padding': 12,
        'autocomplete-form-horizontal-padding': 4,
        'autocomplete-form-border-radius': 12,
        'autocomplete-panel-border-radius': 12,
        'autocomplete-item-border-radius': 8,
        'autocomplete-detached-modal-border-radius': 16,
        'autocomplete-detached-form-padding': 8,
        'autocomplete-form-border-color-alpha': 0.5,
        'autocomplete-form-focus-ring-color-alpha': 0.2,
        'autocomplete-form-focus-ring-width': 3,
        'autocomplete-panel-border-color-alpha': 0.15,
        'autocomplete-panel-padding': 10,
        'autocomplete-item-vertical-padding': 10,
        'autocomplete-item-horizontal-padding': 10,
        'autocomplete-form-input-height': 48,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '109, 40, 217', 0.08),
          shadow(0, 12, 32, -8, '0, 0, 0', 0.15),
        ],
        'autocomplete-item-selected-color': '109, 40, 217',
        'autocomplete-item-selected-alpha': 0.08,
        'autocomplete-item-image-border-radius': 8,
        'autocomplete-item-image-background-color': '255, 255, 255',
        'autocomplete-item-secondary-color': '113, 113, 130',
        'autocomplete-item-emphasis-font-weight': 600,
        'autocomplete-highlight-weight': 700,
        'autocomplete-header-font-weight': 700,
        'autocomplete-header-vertical-margin': 10,
        'autocomplete-header-horizontal-margin': 6,
        'autocomplete-header-letter-spacing': 1,
        'autocomplete-no-results-vertical-padding': 56,
        'autocomplete-no-results-horizontal-padding': 32,
        'autocomplete-no-results-gap': 16,
        'autocomplete-no-results-icon-size': 28,
        'autocomplete-no-results-title-font-weight': 700,
        'autocomplete-no-results-clear-font-weight': 600,
        'autocomplete-no-results-clear-vertical-padding': 10,
        'autocomplete-no-results-clear-horizontal-padding': 24,
        'autocomplete-no-results-clear-border-radius': 8,
      },
      dark: {
        'autocomplete-text-color': '229, 231, 235',
        'autocomplete-background-color': '24, 24, 30',
        'autocomplete-form-border-color': '63, 63, 80',
        'autocomplete-panel-border-color': '63, 63, 80',
        'autocomplete-detached-modal-border-color': '63, 63, 80',
        'autocomplete-detached-form-border-color': '63, 63, 80',
        'autocomplete-form-search-icon-color': '167, 139, 250',
        'autocomplete-form-placeholder-color': '113, 113, 130',
        'autocomplete-form-clear-button-color': '161, 161, 170',
        'autocomplete-header-color': '167, 139, 250',
        'autocomplete-item-icon-color': '113, 113, 130',
        'autocomplete-item-action-color': '167, 139, 250',
        'autocomplete-form-button-horizontal-padding': 12,
        'autocomplete-form-horizontal-padding': 4,
        'autocomplete-form-border-radius': 12,
        'autocomplete-panel-border-radius': 12,
        'autocomplete-item-border-radius': 8,
        'autocomplete-detached-modal-border-radius': 16,
        'autocomplete-detached-form-padding': 8,
        'autocomplete-form-border-color-alpha': 0.4,
        'autocomplete-form-focus-ring-color-alpha': 0.35,
        'autocomplete-form-focus-ring-width': 3,
        'autocomplete-panel-border-color-alpha': 0.15,
        'autocomplete-panel-padding': 10,
        'autocomplete-item-vertical-padding': 10,
        'autocomplete-item-horizontal-padding': 10,
        'autocomplete-form-input-height': 48,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '167, 139, 250', 0.1),
          shadow(0, 12, 32, -8, '0, 0, 0', 0.5),
        ],
        'autocomplete-item-selected-color': '167, 139, 250',
        'autocomplete-item-selected-alpha': 0.15,
        'autocomplete-item-image-border-radius': 8,
        'autocomplete-item-image-background-color': '255, 255, 255',
        'autocomplete-item-secondary-color': '161, 161, 170',
        'autocomplete-item-emphasis-font-weight': 600,
        'autocomplete-highlight-weight': 700,
        'autocomplete-header-font-weight': 700,
        'autocomplete-header-vertical-margin': 10,
        'autocomplete-header-horizontal-margin': 6,
        'autocomplete-header-letter-spacing': 1,
        'autocomplete-no-results-vertical-padding': 56,
        'autocomplete-no-results-horizontal-padding': 32,
        'autocomplete-no-results-gap': 16,
        'autocomplete-no-results-icon-size': 28,
        'autocomplete-no-results-title-font-weight': 700,
        'autocomplete-no-results-clear-font-weight': 600,
        'autocomplete-no-results-clear-vertical-padding': 10,
        'autocomplete-no-results-clear-horizontal-padding': 24,
        'autocomplete-no-results-clear-border-radius': 8,
      },
    },
  },

  // Apple search: airy, borderless, pill-shaped, muted palette.
  {
    name: 'Minimal',
    overrides: {
      light: {
        'autocomplete-form-focus-ring-color': '100, 116, 139',
        'autocomplete-text-color': '51, 65, 85',
        'autocomplete-background-color': '248, 250, 252',
        'autocomplete-form-border-color': '203, 213, 225',
        'autocomplete-panel-border-color': '203, 213, 225',
        'autocomplete-detached-modal-border-color': '203, 213, 225',
        'autocomplete-detached-form-border-color': '203, 213, 225',
        'autocomplete-form-search-icon-color': '100, 116, 139',
        'autocomplete-form-placeholder-color': '148, 163, 184',
        'autocomplete-form-clear-button-color': '148, 163, 184',
        'autocomplete-form-button-horizontal-padding': 8,
        'autocomplete-form-horizontal-padding': 8,
        'autocomplete-header-color': '100, 116, 139',
        'autocomplete-item-icon-color': '148, 163, 184',
        'autocomplete-item-action-color': '100, 116, 139',
        'autocomplete-form-placeholder-color-alpha': 0.5,
        'autocomplete-form-clear-button-color-alpha': 0.5,
        'autocomplete-item-icon-color-alpha': 0.5,
        'autocomplete-item-action-color-alpha': 0.5,
        'autocomplete-form-submit-icon-size': 18,
        'autocomplete-form-clear-icon-size': 18,
        'autocomplete-item-icon-size': 18,
        'autocomplete-form-border-radius': 24,
        'autocomplete-form-border-color-alpha': 0,
        'autocomplete-form-focus-ring-color-alpha': 0.15,
        'autocomplete-panel-border-radius': 16,
        'autocomplete-panel-border-color-alpha': 0,
        'autocomplete-panel-padding': 12,
        'autocomplete-panel-shadow': [
          shadow(0, 4, 16, -2, '100, 116, 139', 0.1),
          shadow(0, 12, 32, -4, '100, 116, 139', 0.08),
        ],
        'autocomplete-form-border-width': 0,
        'autocomplete-panel-border-width': 0,
        'autocomplete-item-border-radius': 10,
        'autocomplete-item-selected-color': '100, 116, 139',
        'autocomplete-item-selected-alpha': 0.06,
        'autocomplete-item-image-size': 56,
        'autocomplete-item-image-border-radius': 8,
        'autocomplete-item-image-padding': 6,
        'autocomplete-item-image-background-color': '255, 255, 255',
        'autocomplete-item-secondary-color': '100, 116, 139',
        'autocomplete-item-emphasis-font-weight': 500,
        'autocomplete-item-highlight-color': '51, 65, 85',
        'autocomplete-item-highlight-background-color': '51, 65, 85',
        'autocomplete-item-highlight-background-color-alpha': 0.06,
        'autocomplete-item-vertical-padding': 10,
        'autocomplete-item-horizontal-padding': 10,
        'autocomplete-header-vertical-margin': 10,
        'autocomplete-header-horizontal-margin': 6,
        'autocomplete-detached-modal-border-radius': 20,
        'autocomplete-detached-form-border-width': 0,
        'autocomplete-no-results-vertical-padding': 56,
        'autocomplete-no-results-horizontal-padding': 32,
        'autocomplete-no-results-gap': 16,
        'autocomplete-no-results-icon-size': 28,
        'autocomplete-no-results-clear-border-radius': 12,
        'autocomplete-no-results-clear-background-color-alpha': 0.03,
      },
      dark: {
        'autocomplete-form-focus-ring-color': '148, 163, 184',
        'autocomplete-text-color': '203, 213, 225',
        'autocomplete-background-color': '30, 41, 59',
        'autocomplete-form-border-color': '51, 65, 85',
        'autocomplete-panel-border-color': '51, 65, 85',
        'autocomplete-detached-modal-border-color': '51, 65, 85',
        'autocomplete-detached-form-border-color': '51, 65, 85',
        'autocomplete-form-search-icon-color': '148, 163, 184',
        'autocomplete-form-placeholder-color': '100, 116, 139',
        'autocomplete-form-clear-button-color': '100, 116, 139',
        'autocomplete-form-button-horizontal-padding': 8,
        'autocomplete-form-horizontal-padding': 8,
        'autocomplete-header-color': '148, 163, 184',
        'autocomplete-item-icon-color': '100, 116, 139',
        'autocomplete-item-action-color': '148, 163, 184',
        'autocomplete-form-placeholder-color-alpha': 0.45,
        'autocomplete-form-clear-button-color-alpha': 0.45,
        'autocomplete-item-icon-color-alpha': 0.45,
        'autocomplete-item-action-color-alpha': 0.45,
        'autocomplete-form-submit-icon-size': 18,
        'autocomplete-form-clear-icon-size': 18,
        'autocomplete-item-icon-size': 18,
        'autocomplete-form-border-radius': 24,
        'autocomplete-form-border-color-alpha': 0,
        'autocomplete-form-focus-ring-color-alpha': 0.2,
        'autocomplete-panel-border-radius': 16,
        'autocomplete-panel-border-color-alpha': 0,
        'autocomplete-panel-padding': 12,
        'autocomplete-panel-shadow': [
          shadow(0, 4, 16, -2, '0, 0, 0', 0.2),
          shadow(0, 12, 32, -4, '0, 0, 0', 0.15),
        ],
        'autocomplete-form-border-width': 0,
        'autocomplete-panel-border-width': 0,
        'autocomplete-item-border-radius': 10,
        'autocomplete-item-selected-color': '148, 163, 184',
        'autocomplete-item-selected-alpha': 0.1,
        'autocomplete-item-image-size': 56,
        'autocomplete-item-image-border-radius': 8,
        'autocomplete-item-image-padding': 6,
        'autocomplete-item-image-background-color': '255, 255, 255',
        'autocomplete-item-secondary-color': '148, 163, 184',
        'autocomplete-item-emphasis-font-weight': 500,
        'autocomplete-item-highlight-color': '148, 163, 184',
        'autocomplete-item-highlight-background-color': '148, 163, 184',
        'autocomplete-item-highlight-background-color-alpha': 0.1,
        'autocomplete-item-vertical-padding': 10,
        'autocomplete-item-horizontal-padding': 10,
        'autocomplete-header-vertical-margin': 10,
        'autocomplete-header-horizontal-margin': 6,
        'autocomplete-detached-modal-border-radius': 20,
        'autocomplete-detached-form-border-width': 0,
        'autocomplete-no-results-vertical-padding': 56,
        'autocomplete-no-results-horizontal-padding': 32,
        'autocomplete-no-results-gap': 16,
        'autocomplete-no-results-icon-size': 28,
        'autocomplete-no-results-clear-border-radius': 12,
        'autocomplete-no-results-clear-background-color-alpha': 0.04,
      },
    },
  },

  // Indie/experimental: heavy borders, chunky, hard offset shadows, raw.
  {
    name: 'Brutalist',
    overrides: {
      light: {
        'autocomplete-form-focus-ring-color': '220, 38, 38',
        'autocomplete-text-color': '10, 10, 10',
        'autocomplete-form-border-color': '10, 10, 10',
        'autocomplete-panel-border-color': '10, 10, 10',
        'autocomplete-detached-modal-border-color': '10, 10, 10',
        'autocomplete-detached-form-border-color': '10, 10, 10',
        'autocomplete-form-search-icon-color': '220, 38, 38',
        'autocomplete-form-placeholder-color': '120, 120, 120',
        'autocomplete-form-clear-button-color': '80, 80, 80',
        'autocomplete-header-color': '220, 38, 38',
        'autocomplete-item-icon-color': '80, 80, 80',
        'autocomplete-item-action-color': '220, 38, 38',
        'autocomplete-highlight-weight': 900,
        'autocomplete-header-font-weight': 800,
        'autocomplete-header-letter-spacing': 1.5,
        'autocomplete-form-border-radius': 0,
        'autocomplete-panel-border-radius': 0,
        'autocomplete-item-border-radius': 0,
        'autocomplete-detached-modal-border-radius': 0,
        'autocomplete-detached-modal-border-width': 3,
        'autocomplete-form-border-width': 3,
        'autocomplete-panel-border-width': 3,
        'autocomplete-detached-form-border-width': 3,
        'autocomplete-detached-form-border-color-alpha': 1,
        'autocomplete-form-border-color-alpha': 1,
        'autocomplete-panel-border-color-alpha': 1,
        'autocomplete-form-input-height': 50,
        'autocomplete-form-horizontal-padding': 6,
        'autocomplete-form-button-horizontal-padding': 12,
        'autocomplete-panel-shadow': [shadow(5, 5, 0, 0, '10, 10, 10', 1)],
        'autocomplete-item-selected-color': '220, 38, 38',
        'autocomplete-item-selected-alpha': 0.12,
        'autocomplete-item-image-border-radius': 0,
        'autocomplete-item-image-padding': 6,
        'autocomplete-item-image-background-color': '255, 255, 255',
        'autocomplete-item-secondary-color': '80, 80, 80',
        'autocomplete-item-emphasis-font-weight': 800,
        'autocomplete-item-highlight-color': '220, 38, 38',
        'autocomplete-item-highlight-background-color': '220, 38, 38',
        'autocomplete-item-highlight-background-color-alpha': 0.04,
        'autocomplete-header-vertical-margin': 10,
        'autocomplete-no-results-icon-size': 36,
        'autocomplete-no-results-title-font-size': 16,
        'autocomplete-no-results-title-font-weight': 800,
        'autocomplete-no-results-clear-font-weight': 700,
        'autocomplete-no-results-clear-vertical-padding': 10,
        'autocomplete-no-results-clear-horizontal-padding': 24,
        'autocomplete-no-results-clear-border-radius': 0,
        'autocomplete-no-results-clear-border-color-alpha': 0.8,
        'autocomplete-no-results-clear-background-color-alpha': 0.1,
        'autocomplete-item-vertical-padding': 10,
        'autocomplete-item-horizontal-padding': 10,
      },
      dark: {
        'autocomplete-form-focus-ring-color': '248, 113, 113',
        'autocomplete-text-color': '245, 245, 245',
        'autocomplete-background-color': '15, 15, 15',
        'autocomplete-form-border-color': '245, 245, 245',
        'autocomplete-panel-border-color': '245, 245, 245',
        'autocomplete-detached-modal-border-color': '245, 245, 245',
        'autocomplete-detached-form-border-color': '245, 245, 245',
        'autocomplete-form-search-icon-color': '248, 113, 113',
        'autocomplete-form-placeholder-color': '120, 120, 120',
        'autocomplete-form-clear-button-color': '180, 180, 180',
        'autocomplete-header-color': '248, 113, 113',
        'autocomplete-item-icon-color': '180, 180, 180',
        'autocomplete-item-action-color': '248, 113, 113',
        'autocomplete-highlight-weight': 900,
        'autocomplete-header-font-weight': 800,
        'autocomplete-header-letter-spacing': 1.5,
        'autocomplete-form-border-radius': 0,
        'autocomplete-panel-border-radius': 0,
        'autocomplete-item-border-radius': 0,
        'autocomplete-detached-modal-border-radius': 0,
        'autocomplete-detached-modal-border-width': 3,
        'autocomplete-form-border-width': 3,
        'autocomplete-panel-border-width': 3,
        'autocomplete-detached-form-border-width': 3,
        'autocomplete-detached-form-border-color-alpha': 1,
        'autocomplete-form-border-color-alpha': 1,
        'autocomplete-panel-border-color-alpha': 1,
        'autocomplete-form-input-height': 50,
        'autocomplete-form-horizontal-padding': 6,
        'autocomplete-form-button-horizontal-padding': 12,
        'autocomplete-panel-shadow': [shadow(5, 5, 0, 0, '245, 245, 245', 1)],
        'autocomplete-item-selected-color': '248, 113, 113',
        'autocomplete-item-selected-alpha': 0.15,
        'autocomplete-item-image-border-radius': 0,
        'autocomplete-item-image-padding': 6,
        'autocomplete-item-image-background-color': '255, 255, 255',
        'autocomplete-item-secondary-color': '180, 180, 180',
        'autocomplete-item-emphasis-font-weight': 800,
        'autocomplete-item-highlight-color': '248, 113, 113',
        'autocomplete-item-highlight-background-color': '248, 113, 113',
        'autocomplete-item-highlight-background-color-alpha': 0.12,
        'autocomplete-header-vertical-margin': 10,
        'autocomplete-no-results-icon-size': 36,
        'autocomplete-no-results-title-font-size': 16,
        'autocomplete-no-results-title-font-weight': 800,
        'autocomplete-no-results-clear-font-weight': 700,
        'autocomplete-no-results-clear-vertical-padding': 10,
        'autocomplete-no-results-clear-horizontal-padding': 24,
        'autocomplete-no-results-clear-border-radius': 0,
        'autocomplete-no-results-clear-border-color-alpha': 0.8,
        'autocomplete-no-results-clear-background-color-alpha': 0.12,
        'autocomplete-item-vertical-padding': 10,
        'autocomplete-item-horizontal-padding': 10,
      },
    },
  },
];
