import type { ShadowLayer, ThemePreset } from '../../types';

function shadow(
  offsetX: number,
  offsetY: number,
  blur: number,
  spread: number,
  color: string,
  opacity: number
): ShadowLayer {
  return { offsetX, offsetY, blur, spread, color, opacity };
}

export const AUTOCOMPLETE_PRESETS: ThemePreset[] = [
  {
    name: 'Default',
    overrides: { light: {}, dark: {} },
  },

  // Apple search: airy, borderless, pill-shaped, muted palette.
  {
    name: 'Minimal',
    overrides: {
      light: {
        'autocomplete-primary-color': '100, 116, 139',
        'autocomplete-text-color': '51, 65, 85',
        'autocomplete-background-color': '248, 250, 252',
        'autocomplete-border-color': '203, 213, 225',
        'autocomplete-search-icon-color': '100, 116, 139',
        'autocomplete-placeholder-color': '148, 163, 184',
        'autocomplete-clear-button-color': '148, 163, 184',
        'autocomplete-header-color': '100, 116, 139',
        'autocomplete-item-icon-color': '148, 163, 184',
        'autocomplete-item-action-color': '100, 116, 139',
        'autocomplete-muted-color-alpha': 0.5,
        'autocomplete-icon-size': 18,
        'autocomplete-icon-stroke-width': 1.4,
        'autocomplete-form-border-radius': 24,
        'autocomplete-form-border-opacity': 0,
        'autocomplete-form-focus-ring-opacity': 0.15,
        'autocomplete-panel-border-radius': 16,
        'autocomplete-panel-border-opacity': 0,
        'autocomplete-panel-padding': 12,
        'autocomplete-panel-gap': 10,
        'autocomplete-panel-shadow': [
          shadow(0, 4, 16, -2, '100, 116, 139', 0.1),
          shadow(0, 12, 32, -4, '100, 116, 139', 0.08),
        ],
        'autocomplete-border-width': 0,
        'autocomplete-item-border-radius': 10,
        'autocomplete-item-selected-opacity': 0.06,
        'autocomplete-item-padding': 6,
        'autocomplete-header-line-opacity': 0.15,
        'autocomplete-header-font-size': 0.72,
        'autocomplete-detached-modal-border-radius': 20,
        'autocomplete-transition-duration': 0.25,
        'autocomplete-scrollbar-width': 3,
        'autocomplete-scrollbar-color-mix': 15,
      },
      dark: {
        'autocomplete-primary-color': '148, 163, 184',
        'autocomplete-text-color': '203, 213, 225',
        'autocomplete-background-color': '30, 41, 59',
        'autocomplete-border-color': '51, 65, 85',
        'autocomplete-search-icon-color': '148, 163, 184',
        'autocomplete-placeholder-color': '100, 116, 139',
        'autocomplete-clear-button-color': '100, 116, 139',
        'autocomplete-header-color': '148, 163, 184',
        'autocomplete-item-icon-color': '100, 116, 139',
        'autocomplete-item-action-color': '148, 163, 184',
        'autocomplete-muted-color-alpha': 0.45,
        'autocomplete-icon-size': 18,
        'autocomplete-icon-stroke-width': 1.4,
        'autocomplete-form-border-radius': 24,
        'autocomplete-form-border-opacity': 0,
        'autocomplete-form-focus-ring-opacity': 0.2,
        'autocomplete-panel-border-radius': 16,
        'autocomplete-panel-border-opacity': 0,
        'autocomplete-panel-padding': 12,
        'autocomplete-panel-gap': 10,
        'autocomplete-panel-shadow': [
          shadow(0, 4, 16, -2, '0, 0, 0', 0.2),
          shadow(0, 12, 32, -4, '0, 0, 0', 0.15),
        ],
        'autocomplete-border-width': 0,
        'autocomplete-item-border-radius': 10,
        'autocomplete-item-selected-opacity': 0.1,
        'autocomplete-item-padding': 6,
        'autocomplete-header-line-opacity': 0.15,
        'autocomplete-header-font-size': 0.72,
        'autocomplete-detached-modal-border-radius': 20,
        'autocomplete-transition-duration': 0.25,
        'autocomplete-scrollbar-width': 3,
        'autocomplete-scrollbar-color-mix': 15,
      },
    },
  },

  // Editorial/newspaper: sharp edges, strong borders, heavy type, snappy.
  {
    name: 'Bold',
    overrides: {
      light: {
        'autocomplete-primary-color': '10, 10, 10',
        'autocomplete-text-color': '10, 10, 10',
        'autocomplete-border-color': '10, 10, 10',
        'autocomplete-search-icon-color': '10, 10, 10',
        'autocomplete-placeholder-color': '140, 140, 140',
        'autocomplete-clear-button-color': '100, 100, 100',
        'autocomplete-header-color': '10, 10, 10',
        'autocomplete-item-icon-color': '80, 80, 80',
        'autocomplete-item-action-color': '10, 10, 10',
        'autocomplete-icon-stroke-width': 2.2,
        'autocomplete-font-weight-medium': 600,
        'autocomplete-highlight-weight': 900,
        'autocomplete-header-font-weight': 700,
        'autocomplete-header-font-size': 0.72,
        'autocomplete-form-border-radius': 0,
        'autocomplete-panel-border-radius': 0,
        'autocomplete-item-border-radius': 0,
        'autocomplete-detached-modal-border-radius': 0,
        'autocomplete-border-width': 2,
        'autocomplete-form-border-opacity': 1,
        'autocomplete-panel-border-opacity': 1,
        'autocomplete-search-input-height': 50,
        'autocomplete-form-padding-left': 20,
        'autocomplete-panel-shadow': [shadow(4, 4, 0, 0, '10, 10, 10', 0.15)],
        'autocomplete-item-selected-opacity': 0.08,
        'autocomplete-header-line-opacity': 0.4,
        'autocomplete-transition-duration': 0.12,
        'autocomplete-scrollbar-color-mix': 40,
      },
      dark: {
        'autocomplete-primary-color': '240, 240, 240',
        'autocomplete-text-color': '240, 240, 240',
        'autocomplete-border-color': '240, 240, 240',
        'autocomplete-search-icon-color': '240, 240, 240',
        'autocomplete-placeholder-color': '120, 120, 120',
        'autocomplete-clear-button-color': '160, 160, 160',
        'autocomplete-header-color': '240, 240, 240',
        'autocomplete-item-icon-color': '180, 180, 180',
        'autocomplete-item-action-color': '240, 240, 240',
        'autocomplete-icon-stroke-width': 2.2,
        'autocomplete-font-weight-medium': 600,
        'autocomplete-highlight-weight': 900,
        'autocomplete-header-font-weight': 700,
        'autocomplete-header-font-size': 0.72,
        'autocomplete-form-border-radius': 0,
        'autocomplete-panel-border-radius': 0,
        'autocomplete-item-border-radius': 0,
        'autocomplete-detached-modal-border-radius': 0,
        'autocomplete-border-width': 2,
        'autocomplete-form-border-opacity': 1,
        'autocomplete-panel-border-opacity': 1,
        'autocomplete-search-input-height': 50,
        'autocomplete-form-padding-left': 20,
        'autocomplete-panel-shadow': [
          shadow(4, 4, 0, 0, '240, 240, 240', 0.15),
        ],
        'autocomplete-item-selected-opacity': 0.12,
        'autocomplete-header-line-opacity': 0.4,
        'autocomplete-transition-duration': 0.12,
        'autocomplete-scrollbar-color-mix': 40,
      },
    },
  },

  // Friendly SaaS: rounded, indigo, spacious, gentle shadows, slow transitions.
  {
    name: 'Soft',
    overrides: {
      light: {
        'autocomplete-primary-color': '79, 70, 229',
        'autocomplete-text-color': '55, 65, 81',
        'autocomplete-background-color': '249, 250, 251',
        'autocomplete-border-color': '196, 200, 220',
        'autocomplete-search-icon-color': '79, 70, 229',
        'autocomplete-placeholder-color': '156, 163, 175',
        'autocomplete-clear-button-color': '156, 163, 175',
        'autocomplete-header-color': '79, 70, 229',
        'autocomplete-item-icon-color': '156, 163, 175',
        'autocomplete-item-action-color': '79, 70, 229',
        'autocomplete-form-border-radius': 14,
        'autocomplete-panel-border-radius': 14,
        'autocomplete-item-border-radius': 10,
        'autocomplete-detached-modal-border-radius': 20,
        'autocomplete-form-border-opacity': 0.5,
        'autocomplete-form-focus-ring-opacity': 0.25,
        'autocomplete-form-focus-ring-width': 3,
        'autocomplete-panel-border-opacity': 0.2,
        'autocomplete-item-selected-opacity': 0.08,
        'autocomplete-panel-padding': 14,
        'autocomplete-panel-gap': 12,
        'autocomplete-item-padding': 8,
        'autocomplete-item-icon-box-size': 34,
        'autocomplete-item-min-height': 46,
        'autocomplete-search-input-height': 48,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '79, 70, 229', 0.06),
          shadow(0, 8, 24, -4, '100, 116, 139', 0.12),
        ],
        'autocomplete-highlight-weight': 600,
        'autocomplete-header-line-opacity': 0.2,
        'autocomplete-transition-duration': 0.4,
        'autocomplete-transition-timing-function':
          'cubic-bezier(0.22, 1, 0.36, 1)',
        'autocomplete-scrollbar-width': 4,
        'autocomplete-scrollbar-color-mix': 20,
      },
      dark: {
        'autocomplete-primary-color': '129, 140, 248',
        'autocomplete-text-color': '209, 213, 219',
        'autocomplete-background-color': '30, 32, 44',
        'autocomplete-border-color': '55, 60, 80',
        'autocomplete-search-icon-color': '129, 140, 248',
        'autocomplete-placeholder-color': '107, 114, 128',
        'autocomplete-clear-button-color': '107, 114, 128',
        'autocomplete-header-color': '129, 140, 248',
        'autocomplete-item-icon-color': '107, 114, 128',
        'autocomplete-item-action-color': '129, 140, 248',
        'autocomplete-form-border-radius': 14,
        'autocomplete-panel-border-radius': 14,
        'autocomplete-item-border-radius': 10,
        'autocomplete-detached-modal-border-radius': 20,
        'autocomplete-form-border-opacity': 0.4,
        'autocomplete-form-focus-ring-opacity': 0.3,
        'autocomplete-form-focus-ring-width': 3,
        'autocomplete-panel-border-opacity': 0.2,
        'autocomplete-item-selected-opacity': 0.12,
        'autocomplete-panel-padding': 14,
        'autocomplete-panel-gap': 12,
        'autocomplete-item-padding': 8,
        'autocomplete-item-icon-box-size': 34,
        'autocomplete-item-min-height': 46,
        'autocomplete-search-input-height': 48,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '129, 140, 248', 0.08),
          shadow(0, 8, 24, -4, '0, 0, 0', 0.3),
        ],
        'autocomplete-highlight-weight': 600,
        'autocomplete-header-line-opacity': 0.2,
        'autocomplete-transition-duration': 0.4,
        'autocomplete-transition-timing-function':
          'cubic-bezier(0.22, 1, 0.36, 1)',
        'autocomplete-scrollbar-width': 4,
        'autocomplete-scrollbar-color-mix': 20,
      },
    },
  },

  // Aesop-inspired: warm neutrals, understated luxury, earthy tones.
  {
    name: 'Warm',
    overrides: {
      light: {
        'autocomplete-primary-color': '146, 95, 55',
        'autocomplete-text-color': '58, 50, 43',
        'autocomplete-background-color': '250, 247, 243',
        'autocomplete-border-color': '210, 200, 188',
        'autocomplete-search-icon-color': '146, 95, 55',
        'autocomplete-placeholder-color': '158, 148, 136',
        'autocomplete-clear-button-color': '158, 148, 136',
        'autocomplete-header-color': '146, 95, 55',
        'autocomplete-item-icon-color': '158, 148, 136',
        'autocomplete-item-action-color': '146, 95, 55',
        'autocomplete-muted-color-alpha': 0.5,
        'autocomplete-icon-size': 18,
        'autocomplete-icon-stroke-width': 1.5,
        'autocomplete-form-border-radius': 8,
        'autocomplete-panel-border-radius': 8,
        'autocomplete-item-border-radius': 6,
        'autocomplete-detached-modal-border-radius': 12,
        'autocomplete-form-border-opacity': 0.4,
        'autocomplete-form-focus-ring-opacity': 0.15,
        'autocomplete-panel-border-opacity': 0.2,
        'autocomplete-panel-padding': 6,
        'autocomplete-panel-gap': 6,
        'autocomplete-item-min-height': 36,
        'autocomplete-search-input-height': 42,
        'autocomplete-panel-shadow': [
          shadow(0, 1, 3, 0, '58, 50, 43', 0.06),
          shadow(0, 4, 12, 0, '58, 50, 43', 0.04),
        ],
        'autocomplete-item-selected-opacity': 0.06,
        'autocomplete-header-line-opacity': 0.15,
        'autocomplete-header-font-size': 0.7,
        'autocomplete-scrollbar-width': 3,
        'autocomplete-scrollbar-color-mix': 15,
      },
      dark: {
        'autocomplete-primary-color': '205, 160, 120',
        'autocomplete-text-color': '230, 222, 214',
        'autocomplete-background-color': '40, 35, 30',
        'autocomplete-border-color': '75, 65, 55',
        'autocomplete-search-icon-color': '205, 160, 120',
        'autocomplete-placeholder-color': '140, 130, 118',
        'autocomplete-clear-button-color': '140, 130, 118',
        'autocomplete-header-color': '205, 160, 120',
        'autocomplete-item-icon-color': '140, 130, 118',
        'autocomplete-item-action-color': '205, 160, 120',
        'autocomplete-muted-color-alpha': 0.45,
        'autocomplete-icon-size': 18,
        'autocomplete-icon-stroke-width': 1.5,
        'autocomplete-form-border-radius': 8,
        'autocomplete-panel-border-radius': 8,
        'autocomplete-item-border-radius': 6,
        'autocomplete-detached-modal-border-radius': 12,
        'autocomplete-form-border-opacity': 0.35,
        'autocomplete-form-focus-ring-opacity': 0.2,
        'autocomplete-panel-border-opacity': 0.2,
        'autocomplete-panel-padding': 6,
        'autocomplete-panel-gap': 6,
        'autocomplete-item-min-height': 36,
        'autocomplete-search-input-height': 42,
        'autocomplete-panel-shadow': [
          shadow(0, 1, 3, 0, '0, 0, 0', 0.15),
          shadow(0, 4, 12, 0, '0, 0, 0', 0.1),
        ],
        'autocomplete-item-selected-opacity': 0.1,
        'autocomplete-header-line-opacity': 0.2,
        'autocomplete-header-font-size': 0.7,
        'autocomplete-scrollbar-width': 3,
        'autocomplete-scrollbar-color-mix': 15,
      },
    },
  },

  // Sustainability/wellness: emerald greens, clean, organic feel.
  {
    name: 'Nature',
    overrides: {
      light: {
        'autocomplete-primary-color': '4, 120, 87',
        'autocomplete-text-color': '20, 60, 50',
        'autocomplete-background-color': '247, 252, 249',
        'autocomplete-border-color': '167, 210, 190',
        'autocomplete-search-icon-color': '4, 120, 87',
        'autocomplete-placeholder-color': '120, 160, 145',
        'autocomplete-clear-button-color': '120, 160, 145',
        'autocomplete-header-color': '4, 120, 87',
        'autocomplete-item-icon-color': '120, 160, 145',
        'autocomplete-item-action-color': '4, 120, 87',
        'autocomplete-form-border-radius': 10,
        'autocomplete-panel-border-radius': 10,
        'autocomplete-item-border-radius': 6,
        'autocomplete-detached-modal-border-radius': 14,
        'autocomplete-form-border-opacity': 0.5,
        'autocomplete-form-focus-ring-opacity': 0.2,
        'autocomplete-panel-border-opacity': 0.25,
        'autocomplete-panel-padding': 10,
        'autocomplete-panel-gap': 8,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '4, 120, 87', 0.06),
          shadow(0, 6, 20, -4, '20, 60, 50', 0.1),
        ],
        'autocomplete-item-selected-opacity': 0.07,
        'autocomplete-header-line-opacity': 0.2,
        'autocomplete-scrollbar-color-mix': 20,
      },
      dark: {
        'autocomplete-primary-color': '52, 211, 153',
        'autocomplete-text-color': '209, 236, 224',
        'autocomplete-background-color': '20, 35, 30',
        'autocomplete-border-color': '45, 75, 65',
        'autocomplete-search-icon-color': '52, 211, 153',
        'autocomplete-placeholder-color': '80, 130, 110',
        'autocomplete-clear-button-color': '80, 130, 110',
        'autocomplete-header-color': '52, 211, 153',
        'autocomplete-item-icon-color': '80, 130, 110',
        'autocomplete-item-action-color': '52, 211, 153',
        'autocomplete-form-border-radius': 10,
        'autocomplete-panel-border-radius': 10,
        'autocomplete-item-border-radius': 6,
        'autocomplete-detached-modal-border-radius': 14,
        'autocomplete-form-border-opacity': 0.4,
        'autocomplete-form-focus-ring-opacity': 0.3,
        'autocomplete-panel-border-opacity': 0.2,
        'autocomplete-panel-padding': 10,
        'autocomplete-panel-gap': 8,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '52, 211, 153', 0.08),
          shadow(0, 6, 20, -4, '0, 0, 0', 0.3),
        ],
        'autocomplete-item-selected-opacity': 0.12,
        'autocomplete-header-line-opacity': 0.25,
        'autocomplete-scrollbar-color-mix': 20,
      },
    },
  },

  // Luxury/premium: violet accent, refined spacing, deep shadows, thin borders.
  {
    name: 'Elegant',
    overrides: {
      light: {
        'autocomplete-primary-color': '109, 40, 217',
        'autocomplete-text-color': '24, 24, 27',
        'autocomplete-border-color': '212, 212, 216',
        'autocomplete-search-icon-color': '109, 40, 217',
        'autocomplete-placeholder-color': '161, 161, 170',
        'autocomplete-clear-button-color': '161, 161, 170',
        'autocomplete-header-color': '109, 40, 217',
        'autocomplete-item-icon-color': '161, 161, 170',
        'autocomplete-item-action-color': '109, 40, 217',
        'autocomplete-font-weight-medium': 600,
        'autocomplete-icon-size': 22,
        'autocomplete-icon-stroke-width': 1.4,
        'autocomplete-form-border-radius': 12,
        'autocomplete-panel-border-radius': 12,
        'autocomplete-item-border-radius': 8,
        'autocomplete-detached-modal-border-radius': 16,
        'autocomplete-form-border-opacity': 0.5,
        'autocomplete-form-focus-ring-opacity': 0.2,
        'autocomplete-form-focus-ring-width': 3,
        'autocomplete-panel-border-opacity': 0.15,
        'autocomplete-panel-padding': 10,
        'autocomplete-panel-gap': 10,
        'autocomplete-item-icon-box-size': 34,
        'autocomplete-item-min-height': 48,
        'autocomplete-item-padding': 6,
        'autocomplete-search-input-height': 48,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '109, 40, 217', 0.08),
          shadow(0, 12, 32, -8, '0, 0, 0', 0.15),
        ],
        'autocomplete-item-selected-opacity': 0.08,
        'autocomplete-highlight-weight': 700,
        'autocomplete-header-font-weight': 700,
        'autocomplete-header-font-size': 0.75,
        'autocomplete-header-line-opacity': 0.2,
        'autocomplete-transition-duration': 0.2,
        'autocomplete-scrollbar-width': 4,
        'autocomplete-scrollbar-color-mix': 25,
      },
      dark: {
        'autocomplete-primary-color': '167, 139, 250',
        'autocomplete-text-color': '229, 231, 235',
        'autocomplete-background-color': '24, 24, 30',
        'autocomplete-border-color': '63, 63, 80',
        'autocomplete-search-icon-color': '167, 139, 250',
        'autocomplete-placeholder-color': '113, 113, 130',
        'autocomplete-clear-button-color': '161, 161, 170',
        'autocomplete-header-color': '167, 139, 250',
        'autocomplete-item-icon-color': '113, 113, 130',
        'autocomplete-item-action-color': '167, 139, 250',
        'autocomplete-font-weight-medium': 600,
        'autocomplete-icon-size': 22,
        'autocomplete-icon-stroke-width': 1.4,
        'autocomplete-form-border-radius': 12,
        'autocomplete-panel-border-radius': 12,
        'autocomplete-item-border-radius': 8,
        'autocomplete-detached-modal-border-radius': 16,
        'autocomplete-form-border-opacity': 0.4,
        'autocomplete-form-focus-ring-opacity': 0.35,
        'autocomplete-form-focus-ring-width': 3,
        'autocomplete-panel-border-opacity': 0.15,
        'autocomplete-panel-padding': 10,
        'autocomplete-panel-gap': 10,
        'autocomplete-item-icon-box-size': 34,
        'autocomplete-item-min-height': 48,
        'autocomplete-item-padding': 6,
        'autocomplete-search-input-height': 48,
        'autocomplete-panel-shadow': [
          shadow(0, 0, 0, 1, '167, 139, 250', 0.1),
          shadow(0, 12, 32, -8, '0, 0, 0', 0.5),
        ],
        'autocomplete-item-selected-opacity': 0.15,
        'autocomplete-highlight-weight': 700,
        'autocomplete-header-font-weight': 700,
        'autocomplete-header-font-size': 0.75,
        'autocomplete-header-line-opacity': 0.2,
        'autocomplete-transition-duration': 0.2,
        'autocomplete-scrollbar-width': 4,
        'autocomplete-scrollbar-color-mix': 25,
      },
    },
  },

  // Indie/experimental: heavy borders, chunky, hard offset shadows, raw.
  {
    name: 'Brutalist',
    overrides: {
      light: {
        'autocomplete-primary-color': '220, 38, 38',
        'autocomplete-text-color': '10, 10, 10',
        'autocomplete-border-color': '10, 10, 10',
        'autocomplete-search-icon-color': '220, 38, 38',
        'autocomplete-placeholder-color': '120, 120, 120',
        'autocomplete-clear-button-color': '80, 80, 80',
        'autocomplete-header-color': '220, 38, 38',
        'autocomplete-item-icon-color': '80, 80, 80',
        'autocomplete-item-action-color': '220, 38, 38',
        'autocomplete-icon-stroke-width': 2.2,
        'autocomplete-font-weight-medium': 700,
        'autocomplete-highlight-weight': 900,
        'autocomplete-header-font-weight': 800,
        'autocomplete-header-font-size': 0.72,
        'autocomplete-form-border-radius': 0,
        'autocomplete-panel-border-radius': 0,
        'autocomplete-item-border-radius': 0,
        'autocomplete-detached-modal-border-radius': 0,
        'autocomplete-border-width': 3,
        'autocomplete-form-border-opacity': 1,
        'autocomplete-panel-border-opacity': 1,
        'autocomplete-search-input-height': 50,
        'autocomplete-form-padding-left': 20,
        'autocomplete-panel-shadow': [shadow(5, 5, 0, 0, '10, 10, 10', 1)],
        'autocomplete-item-selected-opacity': 0.12,
        'autocomplete-header-line-opacity': 0.5,
        'autocomplete-transition-duration': 0.08,
        'autocomplete-scrollbar-width': 8,
        'autocomplete-scrollbar-color-mix': 50,
      },
      dark: {
        'autocomplete-primary-color': '248, 113, 113',
        'autocomplete-text-color': '245, 245, 245',
        'autocomplete-background-color': '15, 15, 15',
        'autocomplete-border-color': '245, 245, 245',
        'autocomplete-search-icon-color': '248, 113, 113',
        'autocomplete-placeholder-color': '120, 120, 120',
        'autocomplete-clear-button-color': '180, 180, 180',
        'autocomplete-header-color': '248, 113, 113',
        'autocomplete-item-icon-color': '180, 180, 180',
        'autocomplete-item-action-color': '248, 113, 113',
        'autocomplete-icon-stroke-width': 2.2,
        'autocomplete-font-weight-medium': 700,
        'autocomplete-highlight-weight': 900,
        'autocomplete-header-font-weight': 800,
        'autocomplete-header-font-size': 0.72,
        'autocomplete-form-border-radius': 0,
        'autocomplete-panel-border-radius': 0,
        'autocomplete-item-border-radius': 0,
        'autocomplete-detached-modal-border-radius': 0,
        'autocomplete-border-width': 3,
        'autocomplete-form-border-opacity': 1,
        'autocomplete-panel-border-opacity': 1,
        'autocomplete-search-input-height': 50,
        'autocomplete-form-padding-left': 20,
        'autocomplete-panel-shadow': [shadow(5, 5, 0, 0, '245, 245, 245', 1)],
        'autocomplete-item-selected-opacity': 0.15,
        'autocomplete-header-line-opacity': 0.5,
        'autocomplete-transition-duration': 0.08,
        'autocomplete-scrollbar-width': 8,
        'autocomplete-scrollbar-color-mix': 50,
      },
    },
  },
];
