import { createThemeOverridesSchema } from '../../lib/create-theme-overrides-schema';

import type { ThemeVariable } from '../..';

export const AUTOCOMPLETE_VARIABLES: ThemeVariable[] = [
  // --- Colors ---
  {
    key: 'autocomplete-text-color',
    label: 'Text color',
    type: 'color',
    alpha: 'autocomplete-text-color-alpha',
    group: 'colors',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Main text color for the autocomplete.',
  },
  {
    key: 'autocomplete-text-color-alpha',
    label: 'Text color alpha',
    type: 'number',
    group: 'colors',
    default: '1',
    description: 'Opacity of the text color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-background-color',
    label: 'Background color',
    type: 'color',
    alpha: 'autocomplete-background-color-alpha',
    group: 'colors',
    default: { light: '255, 255, 255', dark: '38, 38, 38' },
    description: 'Background color for the form and panel.',
  },
  {
    key: 'autocomplete-background-color-alpha',
    label: 'Background color alpha',
    type: 'number',
    group: 'colors',
    default: '1',
    description: 'Opacity of the background color.',
    constraints: { min: 0, max: 1 },
  },

  // --- Typography ---
  {
    key: 'autocomplete-base-unit',
    label: 'Font size',
    type: 'number',
    group: 'typography',
    default: '16',
    description: 'Base font size unit in pixels.',
    constraints: { min: 8, max: 32, step: 1, unit: 'px' },
  },

  // --- Search Input ---
  // Input
  {
    key: 'autocomplete-form-input-height',
    label: 'Form input height',
    shortLabel: 'Height',
    type: 'number',
    group: 'input',
    section: 'Input',
    default: '44',
    description: 'Height of the search input field.',
    constraints: { min: 32, max: 64, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-border-radius',
    label: 'Form corner radius',
    shortLabel: 'Corner radius',
    type: 'number',
    group: 'input',
    section: 'Input',
    default: '4',
    description: 'Corner radius of the search form.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-horizontal-padding',
    label: 'Form horizontal padding',
    shortLabel: 'Horizontal padding',
    type: 'number',
    group: 'input',
    section: 'Input',
    default: '8',
    description: 'Padding on the left and right edges of the search form.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-button-horizontal-padding',
    label: 'Form button padding',
    shortLabel: 'Button padding',
    type: 'number',
    group: 'input',
    section: 'Input',
    default: '4',
    description:
      'Padding around the submit and clear button icons, controlling their click area.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-border-color',
    label: 'Form border color',
    shortLabel: 'Border color',
    type: 'color',
    alpha: 'autocomplete-form-border-color-alpha',
    group: 'input',
    section: 'Input',
    default: { light: '150, 150, 150', dark: '100, 100, 100' },
    description: 'Color of the search form border.',
  },
  {
    key: 'autocomplete-form-border-color-alpha',
    label: 'Form border color alpha',
    type: 'number',
    group: 'input',
    section: 'Input',
    default: '0.8',
    description: 'Opacity of the search form border.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-form-border-width',
    label: 'Form border width',
    shortLabel: 'Border width',
    type: 'number',
    group: 'input',
    section: 'Input',
    default: '1',
    description: 'Width of the search form border.',
    constraints: { min: 0, max: 4, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-placeholder-color',
    label: 'Form placeholder color',
    shortLabel: 'Placeholder color',
    type: 'color',
    alpha: 'autocomplete-form-placeholder-color-alpha',
    group: 'input',
    section: 'Input',
    default: { light: '82, 82, 82', dark: '170, 170, 170' },
    description: 'Color of the placeholder text in the form.',
  },
  {
    key: 'autocomplete-form-placeholder-color-alpha',
    label: 'Form placeholder color alpha',
    type: 'number',
    group: 'input',
    section: 'Input',
    default: '1',
    description: 'Opacity of the placeholder text.',
    constraints: { min: 0, max: 1 },
  },

  // Submit button
  {
    key: 'autocomplete-form-submit-icon-size',
    label: 'Form submit icon size',
    shortLabel: 'Icon size',
    type: 'number',
    group: 'input',
    section: 'Submit button',
    default: '20',
    description: 'Width and height of the search icon.',
    constraints: { min: 12, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-search-icon-color',
    label: 'Form search icon color',
    shortLabel: 'Icon color',
    type: 'color',
    alpha: 'autocomplete-form-search-icon-color-alpha',
    group: 'input',
    section: 'Submit button',
    default: { light: '30, 89, 255', dark: '110, 160, 255' },
    description: 'Color of the search icon in the form.',
  },
  {
    key: 'autocomplete-form-search-icon-color-alpha',
    label: 'Form search icon color alpha',
    type: 'number',
    group: 'input',
    section: 'Submit button',
    default: '1',
    description: 'Opacity of the search icon in the form.',
    constraints: { min: 0, max: 1 },
  },

  // Clear button
  {
    key: 'autocomplete-form-clear-icon-size',
    label: 'Form clear icon size',
    shortLabel: 'Icon size',
    type: 'number',
    group: 'input',
    section: 'Clear button',
    default: '20',
    description: 'Width and height of the clear button icon.',
    constraints: { min: 12, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-clear-button-color',
    label: 'Form clear button color',
    shortLabel: 'Icon color',
    type: 'color',
    alpha: 'autocomplete-form-clear-button-color-alpha',
    group: 'input',
    section: 'Clear button',
    default: { light: '82, 82, 82', dark: '170, 170, 170' },
    description: 'Color of the clear/reset button in the form.',
  },
  {
    key: 'autocomplete-form-clear-button-color-alpha',
    label: 'Form clear button color alpha',
    type: 'number',
    group: 'input',
    section: 'Clear button',
    default: '1',
    description: 'Opacity of the clear/reset button.',
    constraints: { min: 0, max: 1 },
  },

  // Focus ring
  {
    key: 'autocomplete-form-focus-ring-color',
    label: 'Focus ring color',
    shortLabel: 'Color',
    type: 'color',
    alpha: 'autocomplete-form-focus-ring-color-alpha',
    group: 'input',
    section: 'Focus ring',
    default: { light: '109, 40, 217', dark: '167, 139, 250' },
    description: 'Color of the focus ring around the search form.',
  },
  {
    key: 'autocomplete-form-focus-ring-color-alpha',
    label: 'Focus ring opacity',
    shortLabel: 'Opacity',
    type: 'number',
    group: 'input',
    section: 'Focus ring',
    default: '0.2',
    description: 'Opacity of the focus ring glow around the search form.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-form-focus-ring-width',
    label: 'Focus ring width',
    shortLabel: 'Width',
    type: 'number',
    group: 'input',
    section: 'Focus ring',
    default: '2',
    description: 'Width of the focus ring around the search form.',
    constraints: { min: 0, max: 8, step: 1, unit: 'px' },
  },

  // --- Results Panel ---
  // Panel
  {
    key: 'autocomplete-panel-margin-top',
    label: 'Panel margin top',
    shortLabel: 'Top offset',
    type: 'number',
    group: 'panel',
    section: 'Panel',
    default: '8',
    description: 'Gap between the search form and the results panel.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-max-height',
    label: 'Panel max height',
    shortLabel: 'Max height',
    type: 'number',
    group: 'panel',
    section: 'Panel',
    default: '650',
    description: 'Maximum height of the autocomplete results panel.',
    constraints: { min: 200, max: 1000, step: 10, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-padding',
    label: 'Panel padding',
    shortLabel: 'Padding',
    type: 'number',
    group: 'panel',
    section: 'Panel',
    default: '8',
    description: 'Inner padding of the panel.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-border-radius',
    label: 'Panel corner radius',
    shortLabel: 'Corner radius',
    type: 'number',
    group: 'panel',
    section: 'Panel',
    default: '4',
    description: 'Corner radius of the results panel.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-border-color',
    label: 'Panel border color',
    shortLabel: 'Border color',
    type: 'color',
    alpha: 'autocomplete-panel-border-color-alpha',
    group: 'panel',
    section: 'Panel',
    default: { light: '150, 150, 150', dark: '100, 100, 100' },
    description: 'Color of the results panel border.',
  },
  {
    key: 'autocomplete-panel-border-color-alpha',
    label: 'Panel border color alpha',
    type: 'number',
    group: 'panel',
    section: 'Panel',
    default: '0.2',
    description: 'Opacity of the results panel border.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-panel-border-width',
    label: 'Panel border width',
    shortLabel: 'Border width',
    type: 'number',
    group: 'panel',
    section: 'Panel',
    default: '1',
    description: 'Width of the results panel border.',
    constraints: { min: 0, max: 4, step: 1, unit: 'px' },
  },
  // Columns
  {
    key: 'autocomplete-panel-columns',
    label: 'Panel column sizes',
    shortLabel: 'Column sizes',
    type: 'text',
    group: 'panel',
    section: 'Columns',
    default: '1fr 1fr',
    description:
      'CSS grid column sizes for the two-column layout (e.g. "1fr 2fr", "300px 1fr").',
  },
  {
    key: 'autocomplete-panel-columns-breakpoint',
    label: 'Panel columns breakpoint',
    shortLabel: 'Breakpoint',
    type: 'number',
    group: 'panel',
    section: 'Columns',
    default: '680',
    description:
      'Viewport width in pixels below which the two-column layout collapses to a single column.',
    constraints: { min: 0, max: 1920, step: 10, unit: 'px' },
  },
  // Shadow
  {
    key: 'autocomplete-panel-shadow',
    label: 'Panel shadow',
    shortLabel: 'Shadow',
    type: 'shadow',
    group: 'panel',
    section: 'Shadows',
    default: [
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 1,
        color: '23, 23, 23',
        opacity: 0.05,
      },
      {
        offsetX: 0,
        offsetY: 6,
        blur: 16,
        spread: -4,
        color: '23, 23, 23',
        opacity: 0.15,
      },
    ],
    description: 'Box shadow of the results panel.',
  },
  // --- Result Items ---
  // Item
  {
    key: 'autocomplete-item-border-radius',
    label: 'Item corner radius',
    shortLabel: 'Corner radius',
    type: 'number',
    group: 'items',
    section: 'Item',
    default: '4',
    description: 'Corner radius of result items.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-vertical-padding',
    label: 'Item vertical padding',
    shortLabel: 'Vertical padding',
    type: 'number',
    group: 'items',
    section: 'Item',
    default: '4',
    description: 'Top and bottom padding of each result item.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-horizontal-padding',
    label: 'Item horizontal padding',
    shortLabel: 'Horizontal padding',
    type: 'number',
    group: 'items',
    section: 'Item',
    default: '4',
    description: 'Left and right padding of each result item.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-selected-color',
    label: 'Selected item color',
    shortLabel: 'Selected color',
    type: 'color',
    alpha: 'autocomplete-item-selected-alpha',
    group: 'items',
    section: 'Item',
    default: { light: '30, 89, 255', dark: '110, 160, 255' },
    description: 'Background color of the selected/hovered item.',
  },
  {
    key: 'autocomplete-item-selected-alpha',
    label: 'Selected item alpha',
    type: 'number',
    group: 'items',
    section: 'Item',
    default: '0.1',
    description: 'Background opacity of the selected/hovered item.',
    constraints: { min: 0, max: 1 },
  },

  // Suggestions
  {
    key: 'autocomplete-item-icon-color',
    label: 'Item icon color',
    shortLabel: 'Icon color',
    type: 'color',
    alpha: 'autocomplete-item-icon-color-alpha',
    group: 'items',
    section: 'Suggestions',
    default: { light: '82, 82, 82', dark: '170, 170, 170' },
    description: 'Color of icons inside result items.',
  },
  {
    key: 'autocomplete-item-icon-color-alpha',
    label: 'Item icon color alpha',
    type: 'number',
    group: 'items',
    section: 'Suggestions',
    default: '1',
    description: 'Opacity of icons inside result items.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-item-action-color',
    label: 'Item action color',
    shortLabel: 'Action icon color',
    type: 'color',
    alpha: 'autocomplete-item-action-color-alpha',
    group: 'items',
    section: 'Suggestions',
    default: { light: '82, 82, 82', dark: '170, 170, 170' },
    description: 'Color of action buttons inside result items.',
  },
  {
    key: 'autocomplete-item-action-color-alpha',
    label: 'Item action color alpha',
    type: 'number',
    group: 'items',
    section: 'Suggestions',
    default: '1',
    description: 'Opacity of action buttons inside result items.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-item-icon-size',
    label: 'Item icon size',
    shortLabel: 'Icon size',
    type: 'number',
    group: 'items',
    section: 'Suggestions',
    default: '20',
    description: 'Width and height of icons inside result items.',
    constraints: { min: 12, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-gap',
    label: 'Item gap',
    shortLabel: 'Content gap',
    type: 'number',
    group: 'items',
    section: 'Suggestions',
    default: '8',
    description: 'Gap between icon and text within an item.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-action-icon-gap',
    label: 'Item action icon gap',
    shortLabel: 'Action gap',
    type: 'number',
    group: 'items',
    section: 'Suggestions',
    default: '8',
    description: 'Space around icons inside item action buttons.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-action-icon-margin',
    label: 'Item action icon margin',
    type: 'number',
    group: 'items',
    section: 'Suggestions',
    default: '4',
    description: 'Margin around icons inside item action buttons.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-highlight-weight',
    label: 'Highlight weight',
    type: 'number',
    group: 'items',
    section: 'Suggestions',
    default: '700',
    description: 'Font weight for highlighted/matched text.',
    constraints: { min: 100, max: 900, step: 100 },
  },

  // Results — Image
  {
    key: 'autocomplete-item-image-size',
    label: 'Image size',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '80',
    description: 'Width and height of the result image.',
    constraints: { min: 32, max: 160, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-image-border-radius',
    label: 'Image corner radius',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '5',
    description: 'Corner radius of the result image.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-image-padding',
    label: 'Image padding',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '4',
    description: 'Space between the image and its container edges.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-image-background-color',
    label: 'Image background',
    type: 'color',
    alpha: 'autocomplete-item-image-background-color-alpha',
    group: 'items',
    section: 'Results',
    default: { light: '243, 244, 246', dark: '55, 55, 60' },
    description: 'Background color of the image container.',
  },
  {
    key: 'autocomplete-item-image-background-color-alpha',
    label: 'Image background alpha',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '1',
    description: 'Opacity of the image container background.',
    constraints: { min: 0, max: 1 },
  },

  // Results — Content
  {
    key: 'autocomplete-item-content-gap',
    label: 'Content gap',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '12',
    description: 'Gap between image and text within an item.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-info-gap',
    label: 'Text line gap',
    shortLabel: 'Text gap',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '4',
    description:
      'Vertical spacing between name, category, and description lines.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-emphasis-font-weight',
    label: 'Title & price weight',
    shortLabel: 'Title weight',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '600',
    description: 'Font weight of the result name and price.',
    constraints: { min: 100, max: 900, step: 100 },
  },
  {
    key: 'autocomplete-item-secondary-font-size',
    label: 'Details font size',
    shortLabel: 'Details size',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '14',
    description: 'Font size of category and description text.',
    constraints: { min: 8, max: 20, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-secondary-color',
    label: 'Details color',
    type: 'color',
    alpha: 'autocomplete-item-secondary-color-alpha',
    group: 'items',
    section: 'Results',
    default: { light: '107, 114, 128', dark: '156, 163, 175' },
    description: 'Text color of category and description.',
  },
  {
    key: 'autocomplete-item-secondary-color-alpha',
    label: 'Details color alpha',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '1',
    description: 'Opacity of the details text color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-item-highlight-color',
    label: 'Highlight text color',
    shortLabel: 'Highlight color',
    type: 'color',
    alpha: 'autocomplete-item-highlight-color-alpha',
    group: 'items',
    section: 'Results',
    default: { light: '109, 40, 217', dark: '167, 139, 250' },
    description: 'Text color of highlighted search matches.',
  },
  {
    key: 'autocomplete-item-highlight-color-alpha',
    label: 'Highlight text color alpha',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '1',
    description: 'Opacity of the highlight text color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-item-highlight-background-color',
    label: 'Highlight background',
    type: 'color',
    alpha: 'autocomplete-item-highlight-background-color-alpha',
    group: 'items',
    section: 'Results',
    default: { light: '109, 40, 217', dark: '167, 139, 250' },
    description: 'Background color of highlighted search matches.',
  },
  {
    key: 'autocomplete-item-highlight-background-color-alpha',
    label: 'Highlight background alpha',
    type: 'number',
    group: 'items',
    section: 'Results',
    default: '0.08',
    description: 'Opacity of the highlight background color.',
    constraints: { min: 0, max: 1 },
  },

  // --- Section Headers ---
  {
    key: 'autocomplete-header-color',
    label: 'Header color',
    shortLabel: 'Color',
    type: 'color',
    alpha: 'autocomplete-header-color-alpha',
    group: 'headers',
    section: 'Text',
    default: { light: '30, 89, 255', dark: '110, 160, 255' },
    description: 'Color of section header text.',
  },
  {
    key: 'autocomplete-header-color-alpha',
    label: 'Header color alpha',
    shortLabel: 'Opacity',
    type: 'number',
    group: 'headers',
    section: 'Text',
    default: '1',
    description: 'Opacity of the section header text color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-header-font-size',
    label: 'Header font size',
    shortLabel: 'Font size',
    type: 'number',
    group: 'headers',
    section: 'Text',
    default: '13',
    description: 'Font size of section headers.',
    constraints: { min: 8, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-header-font-weight',
    label: 'Header font weight',
    shortLabel: 'Font weight',
    type: 'number',
    group: 'headers',
    section: 'Text',
    default: '600',
    description: 'Font weight of section headers.',
    constraints: { min: 100, max: 900, step: 100 },
  },
  {
    key: 'autocomplete-header-letter-spacing',
    label: 'Header letter spacing',
    shortLabel: 'Letter spacing',
    type: 'number',
    group: 'headers',
    section: 'Text',
    default: '1',
    description: 'Letter spacing for section headers.',
    constraints: { min: -1, max: 5, step: 0.5, unit: 'px' },
  },
  {
    key: 'autocomplete-header-text-transform',
    label: 'Header text transform',
    shortLabel: 'Text transform',
    type: 'select',
    constraints: {
      options: [
        'none',
        'capitalize',
        'uppercase',
        'lowercase',
        'full-width',
        'full-size-kana',
      ],
    },
    group: 'headers',
    section: 'Text',
    default: 'uppercase',
    description: 'Text transform applied to section headers.',
  },
  {
    key: 'autocomplete-header-vertical-margin',
    label: 'Header vertical margin',
    shortLabel: 'Vertical margin',
    type: 'number',
    group: 'headers',
    section: 'Spacing',
    default: '8',
    description: 'Space above and below section headers.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-header-horizontal-margin',
    label: 'Header horizontal margin',
    shortLabel: 'Horizontal margin',
    type: 'number',
    group: 'headers',
    section: 'Spacing',
    default: '4',
    description:
      'Left and right margin of section headers. Use to align with item content.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },

  // --- No Results – Layout ---
  {
    key: 'autocomplete-no-results-vertical-padding',
    label: 'No results vertical padding',
    shortLabel: 'Vertical padding',
    type: 'number',
    group: 'noResults',
    section: 'Layout',
    default: '48',
    description: 'Vertical padding around the no results empty state.',
    constraints: { min: 0, max: 96, step: 4, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-horizontal-padding',
    label: 'No results horizontal padding',
    shortLabel: 'Horizontal padding',
    type: 'number',
    group: 'noResults',
    section: 'Layout',
    default: '24',
    description: 'Horizontal padding around the no results empty state.',
    constraints: { min: 0, max: 96, step: 4, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-gap',
    label: 'No results gap',
    shortLabel: 'Gap',
    type: 'number',
    group: 'noResults',
    section: 'Layout',
    default: '12',
    description: 'Gap between elements in the no results state.',
    constraints: { min: 0, max: 48, step: 2, unit: 'px' },
  },

  // --- No Results – Icon ---
  {
    key: 'autocomplete-no-results-icon-color',
    label: 'No results icon color',
    shortLabel: 'Color',
    type: 'color',
    alpha: 'autocomplete-no-results-icon-color-alpha',
    group: 'noResults',
    section: 'Icon',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Color of the search icon in the no results state.',
  },
  {
    key: 'autocomplete-no-results-icon-color-alpha',
    label: 'No results icon opacity',
    shortLabel: 'Opacity',
    type: 'number',
    group: 'noResults',
    section: 'Icon',
    default: '0.4',
    description: 'Opacity of the search icon in the no results state.',
    constraints: { min: 0, max: 1, step: 0.05 },
  },
  {
    key: 'autocomplete-no-results-icon-size',
    label: 'No results icon size',
    shortLabel: 'Size',
    type: 'number',
    group: 'noResults',
    section: 'Icon',
    default: '24',
    description: 'Size of the search icon in the no results state.',
    constraints: { min: 12, max: 48, step: 2, unit: 'px' },
  },

  // --- No Results – Title ---
  {
    key: 'autocomplete-no-results-title-color',
    label: 'No results title color',
    shortLabel: 'Color',
    type: 'color',
    alpha: 'autocomplete-no-results-title-color-alpha',
    group: 'noResults',
    section: 'Title',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Color of the no results title text.',
  },
  {
    key: 'autocomplete-no-results-title-color-alpha',
    label: 'No results title opacity',
    shortLabel: 'Opacity',
    type: 'number',
    group: 'noResults',
    section: 'Title',
    default: '1',
    description: 'Opacity of the no results title text.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-no-results-title-font-size',
    label: 'No results title font size',
    shortLabel: 'Font size',
    type: 'number',
    group: 'noResults',
    section: 'Title',
    default: '18',
    description: 'Font size of the no results title.',
    constraints: { min: 12, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-title-font-weight',
    label: 'No results title font weight',
    shortLabel: 'Font weight',
    type: 'number',
    group: 'noResults',
    section: 'Title',
    default: '600',
    description: 'Font weight of the no results title.',
    constraints: { min: 100, max: 900, step: 100 },
  },

  // --- No Results – Description ---
  {
    key: 'autocomplete-no-results-description-color',
    label: 'No results description color',
    shortLabel: 'Color',
    type: 'color',
    alpha: 'autocomplete-no-results-description-color-alpha',
    group: 'noResults',
    section: 'Description',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Color of the no results description text.',
  },
  {
    key: 'autocomplete-no-results-description-color-alpha',
    label: 'No results description opacity',
    shortLabel: 'Opacity',
    type: 'number',
    group: 'noResults',
    section: 'Description',
    default: '0.5',
    description: 'Opacity of the no results description text.',
    constraints: { min: 0, max: 1, step: 0.05 },
  },
  {
    key: 'autocomplete-no-results-description-font-size',
    label: 'No results description font size',
    shortLabel: 'Font size',
    type: 'number',
    group: 'noResults',
    section: 'Description',
    default: '14',
    description: 'Font size of the no results description text.',
    constraints: { min: 10, max: 24, step: 1, unit: 'px' },
  },

  // --- No Results – Clear Button ---
  {
    key: 'autocomplete-no-results-clear-color',
    label: 'No results clear button text color',
    shortLabel: 'Text color',
    type: 'color',
    alpha: 'autocomplete-no-results-clear-color-alpha',
    group: 'noResults',
    section: 'Clear Button',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Text color of the clear query button.',
  },
  {
    key: 'autocomplete-no-results-clear-color-alpha',
    label: 'No results clear button text opacity',
    shortLabel: 'Text opacity',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '1',
    description: 'Text opacity of the clear query button.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-no-results-clear-background-color',
    label: 'No results clear button background color',
    shortLabel: 'Background color',
    type: 'color',
    alpha: 'autocomplete-no-results-clear-background-color-alpha',
    group: 'noResults',
    section: 'Clear Button',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Background color of the clear query button.',
  },
  {
    key: 'autocomplete-no-results-clear-background-color-alpha',
    label: 'No results clear button background opacity',
    shortLabel: 'Background opacity',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '0.05',
    description: 'Background opacity of the clear query button.',
    constraints: { min: 0, max: 0.3, step: 0.01 },
  },
  {
    key: 'autocomplete-no-results-clear-border-color',
    label: 'No results clear button border color',
    shortLabel: 'Border color',
    type: 'color',
    alpha: 'autocomplete-no-results-clear-border-color-alpha',
    group: 'noResults',
    section: 'Clear Button',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Border color of the clear query button.',
  },
  {
    key: 'autocomplete-no-results-clear-border-color-alpha',
    label: 'No results clear button border opacity',
    shortLabel: 'Border opacity',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '0.15',
    description: 'Border opacity of the clear query button.',
    constraints: { min: 0, max: 1, step: 0.05 },
  },
  {
    key: 'autocomplete-no-results-clear-border-width',
    label: 'No results clear button border width',
    shortLabel: 'Border width',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '1',
    description: 'Border width of the clear query button.',
    constraints: { min: 0, max: 4, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-font-size',
    label: 'No results clear button font size',
    shortLabel: 'Font size',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '14',
    description: 'Font size of the clear query button.',
    constraints: { min: 10, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-font-weight',
    label: 'No results clear button font weight',
    shortLabel: 'Font weight',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '500',
    description: 'Font weight of the clear query button.',
    constraints: { min: 100, max: 900, step: 100 },
  },
  {
    key: 'autocomplete-no-results-clear-border-radius',
    label: 'No results clear button corner radius',
    shortLabel: 'Corner radius',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '6',
    description: 'Corner radius of the clear query button.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-vertical-padding',
    label: 'No results clear button vertical padding',
    shortLabel: 'Vertical padding',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '8',
    description: 'Vertical padding inside the clear query button.',
    constraints: { min: 0, max: 24, step: 2, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-horizontal-padding',
    label: 'No results clear button horizontal padding',
    shortLabel: 'Horizontal padding',
    type: 'number',
    group: 'noResults',
    section: 'Clear Button',
    default: '20',
    description: 'Horizontal padding inside the clear query button.',
    constraints: { min: 0, max: 48, step: 2, unit: 'px' },
  },

  // --- Detached Mode – Overlay ---
  {
    key: 'autocomplete-overlay-color',
    label: 'Overlay color',
    shortLabel: 'Color',
    type: 'color',
    alpha: 'autocomplete-overlay-color-alpha',
    group: 'detached',
    section: 'Overlay',
    default: '115, 114, 129',
    description: 'Backdrop overlay color in detached mode.',
  },
  {
    key: 'autocomplete-overlay-color-alpha',
    label: 'Overlay color alpha',
    shortLabel: 'Color alpha',
    type: 'number',
    group: 'detached',
    section: 'Overlay',
    default: '0.4',
    description: 'Opacity of the detached mode backdrop overlay.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-overlay-z-index',
    label: 'Overlay z-index',
    shortLabel: 'Z-index',
    type: 'number',
    group: 'detached',
    section: 'Overlay',
    default: '9999',
    description:
      'Z-index of the backdrop overlay in detached mode. Should be below the modal z-index.',
    constraints: { min: 1, max: 2147483647, step: 1 },
  },

  // --- Detached Mode – Modal ---
  {
    key: 'autocomplete-z-index',
    label: 'Z-index',
    type: 'number',
    group: 'detached',
    section: 'Modal',
    default: '10000',
    description:
      'Z-index of the detached modal. Increase if it appears behind other elements on the page.',
    constraints: { min: 1, max: 2147483647, step: 1 },
  },
  {
    key: 'autocomplete-detached-modal-top',
    label: 'Detached modal top offset',
    shortLabel: 'Top offset',
    type: 'number',
    group: 'detached',
    section: 'Modal',
    default: '40',
    description: 'Top offset of the detached modal from viewport.',
    constraints: { min: 0, max: 200, step: 4, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-max-width',
    label: 'Detached modal max width',
    shortLabel: 'Max width',
    type: 'number',
    group: 'detached',
    section: 'Modal',
    default: '680',
    description: 'Maximum width of the detached modal.',
    constraints: { min: 400, max: 1200, step: 10, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-max-height',
    label: 'Detached modal max height',
    shortLabel: 'Max height',
    type: 'number',
    group: 'detached',
    section: 'Modal',
    default: '500',
    description: 'Maximum height of the detached modal.',
    constraints: { min: 300, max: 1000, step: 10, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-border-radius',
    label: 'Detached modal corner radius',
    shortLabel: 'Corner radius',
    type: 'number',
    group: 'detached',
    section: 'Modal',
    default: '8',
    description: 'Corner radius of the detached modal.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-border-color',
    label: 'Detached modal border color',
    shortLabel: 'Border color',
    type: 'color',
    alpha: 'autocomplete-detached-modal-border-color-alpha',
    group: 'detached',
    section: 'Modal',
    default: { light: '150, 150, 150', dark: '100, 100, 100' },
    description: 'Color of the detached modal border.',
  },
  {
    key: 'autocomplete-detached-modal-border-color-alpha',
    label: 'Detached modal border color alpha',
    shortLabel: 'Border color alpha',
    type: 'number',
    group: 'detached',
    section: 'Modal',
    default: '1',
    description: 'Opacity of the detached modal border.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-detached-modal-border-width',
    label: 'Detached modal border width',
    shortLabel: 'Border width',
    type: 'number',
    group: 'detached',
    section: 'Modal',
    default: '0',
    description: 'Border width of the detached modal container.',
    constraints: { min: 0, max: 4, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-shadow',
    label: 'Detached modal shadow',
    shortLabel: 'Shadow',
    type: 'shadow',
    group: 'detached',
    section: 'Modal',
    default: [
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 1,
        color: '23, 23, 23',
        opacity: 0.05,
      },
      {
        offsetX: 0,
        offsetY: 6,
        blur: 16,
        spread: -4,
        color: '23, 23, 23',
        opacity: 0.15,
      },
    ],
    description: 'Box shadow of the detached modal.',
  },

  // --- Detached Mode – Form ---
  {
    key: 'autocomplete-detached-form-padding',
    label: 'Detached form padding',
    shortLabel: 'Padding',
    type: 'number',
    group: 'detached',
    section: 'Form',
    default: '6',
    description: 'Padding around the form inside the detached container.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-form-border-color',
    label: 'Detached form border color',
    shortLabel: 'Border color',
    type: 'color',
    alpha: 'autocomplete-detached-form-border-color-alpha',
    group: 'detached',
    section: 'Form',
    default: { light: '150, 150, 150', dark: '100, 100, 100' },
    description: 'Color of the form border in detached mode.',
  },
  {
    key: 'autocomplete-detached-form-border-color-alpha',
    label: 'Detached form border color alpha',
    shortLabel: 'Border color alpha',
    type: 'number',
    group: 'detached',
    section: 'Form',
    default: '0.3',
    description: 'Opacity of the form border in detached mode.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-detached-form-border-width',
    label: 'Detached form border width',
    shortLabel: 'Border width',
    type: 'number',
    group: 'detached',
    section: 'Form',
    default: '1',
    description: 'Width of the bottom border on the detached form container.',
    constraints: { min: 0, max: 4, step: 1, unit: 'px' },
  },
];

export const autocompleteOverridesSchema = createThemeOverridesSchema(
  AUTOCOMPLETE_VARIABLES
);
