import { createThemeOverridesSchema } from '../../lib/create-theme-overrides-schema';

import type { ThemeVariable } from '../..';

export const AUTOCOMPLETE_VARIABLES: ThemeVariable[] = [
  // --- Colors ---
  {
    key: 'autocomplete-primary-color',
    label: 'Primary color',
    type: 'color',
    group: 'colors',
    default: { light: '30, 89, 255', dark: '110, 160, 255' },
    description:
      'Primary brand color for interactive elements (focus ring, selected item).',
  },
  {
    key: 'autocomplete-primary-color-alpha',
    label: 'Primary color alpha',
    type: 'number',
    group: 'colors',
    default: '1',
    description: 'Opacity of the primary color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-text-color',
    label: 'Text color',
    type: 'color',
    group: 'colors',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Main text color for the autocomplete.',
  },
  {
    key: 'autocomplete-text-color-alpha',
    label: 'Text color alpha',
    type: 'number',
    group: 'colors',
    default: '1',
    description: 'Opacity of the text color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-muted-color-alpha',
    label: 'Muted color alpha',
    type: 'number',
    group: 'colors',
    default: '1',
    description:
      'Opacity for secondary elements (placeholder, clear button, item icons).',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-background-color',
    label: 'Background color',
    type: 'color',
    group: 'colors',
    default: { light: '255, 255, 255', dark: '38, 38, 38' },
    description: 'Background color for the form and panel.',
  },
  {
    key: 'autocomplete-background-color-alpha',
    label: 'Background color alpha',
    type: 'number',
    group: 'colors',
    default: '1',
    description: 'Opacity of the background color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-border-color',
    label: 'Border color',
    type: 'color',
    group: 'colors',
    default: { light: '150, 150, 150', dark: '100, 100, 100' },
    description: 'Color for borders and dividers.',
  },
  {
    key: 'autocomplete-border-width',
    label: 'Border width',
    type: 'number',
    group: 'colors',
    default: '1',
    description: 'Width of borders on the form and panel.',
    constraints: { min: 0, max: 4, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-overlay-color',
    label: 'Overlay color',
    type: 'color',
    group: 'colors',
    default: '115, 114, 129',
    description: 'Backdrop overlay color in detached mode.',
  },
  {
    key: 'autocomplete-overlay-color-alpha',
    label: 'Overlay color alpha',
    type: 'number',
    group: 'colors',
    default: '0.4',
    description: 'Opacity of the detached mode backdrop overlay.',
    constraints: { min: 0, max: 1 },
  },

  // --- Typography ---
  {
    key: 'autocomplete-base-unit',
    label: 'Base unit',
    type: 'number',
    group: 'typography',
    default: '16',
    description: 'Base font size unit in pixels.',
    constraints: { min: 8, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-font-weight-medium',
    label: 'Medium font weight',
    type: 'number',
    group: 'typography',
    default: '500',
    description: 'Font weight for item titles.',
    constraints: { min: 100, max: 900, step: 100 },
  },

  // --- Icons ---
  {
    key: 'autocomplete-icon-size',
    label: 'Icon size',
    type: 'number',
    group: 'icons',
    default: '20',
    description: 'Width and height of icons.',
    constraints: { min: 12, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-icon-stroke-width',
    label: 'Icon stroke width',
    type: 'number',
    group: 'icons',
    default: '1.6',
    description: 'Stroke width for line icons.',
    constraints: { min: 1, max: 3, step: 0.1 },
  },

  // --- Transitions ---
  {
    key: 'autocomplete-transition-duration',
    label: 'Transition duration',
    type: 'number',
    group: 'transitions',
    default: '0.3',
    description: 'Duration for hover and state transitions.',
    constraints: { min: 0, max: 2, step: 0.1, unit: 's' },
  },
  {
    key: 'autocomplete-transition-timing-function',
    label: 'Transition timing',
    type: 'text',
    group: 'transitions',
    default: 'cubic-bezier(0.4, 0, 0.2, 1)',
    description: 'Easing function for transitions.',
  },

  // --- Input ---
  {
    key: 'autocomplete-search-input-height',
    label: 'Search input height',
    type: 'number',
    group: 'input',
    default: '44',
    description: 'Height of the search input field.',
    constraints: { min: 32, max: 64, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-padding-left',
    label: 'Form padding left',
    type: 'number',
    group: 'input',
    default: '16',
    description: 'Left padding inside the form, before the search icon.',
    constraints: { min: 4, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-padding-right',
    label: 'Form padding right',
    type: 'number',
    group: 'input',
    default: '12',
    description: 'Right padding inside the form, after the clear button.',
    constraints: { min: 4, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-border-radius',
    label: 'Form border radius',
    type: 'number',
    group: 'input',
    default: '4',
    description: 'Border radius of the search form.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-form-border-opacity',
    label: 'Form border opacity',
    type: 'number',
    group: 'input',
    default: '0.8',
    description: 'Opacity of the search form border.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-form-focus-ring-opacity',
    label: 'Focus ring opacity',
    type: 'number',
    group: 'input',
    default: '0.2',
    description: 'Opacity of the focus ring around the search form.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-form-focus-ring-width',
    label: 'Focus ring width',
    type: 'number',
    group: 'input',
    default: '2',
    description: 'Width of the focus ring around the search form.',
    constraints: { min: 0, max: 8, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-search-icon-color',
    label: 'Search icon color',
    type: 'color',
    group: 'colors',
    default: '30, 89, 255',
    description: 'Color of the search icon in the input.',
  },
  {
    key: 'autocomplete-placeholder-color',
    label: 'Placeholder color',
    type: 'color',
    group: 'colors',
    default: '82, 82, 82',
    description: 'Color of the placeholder text in the input.',
  },
  {
    key: 'autocomplete-clear-button-color',
    label: 'Clear button color',
    type: 'color',
    group: 'colors',
    default: '82, 82, 82',
    description: 'Color of the clear/reset button in the input.',
  },

  // --- Panel ---
  {
    key: 'autocomplete-panel-margin-top',
    label: 'Panel margin top',
    type: 'number',
    group: 'panel',
    default: '8',
    description: 'Gap between the search form and the results panel.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-max-height',
    label: 'Panel max height',
    type: 'number',
    group: 'panel',
    default: '650',
    description: 'Maximum height of the autocomplete results panel.',
    constraints: { min: 200, max: 1000, step: 10, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-border-radius',
    label: 'Panel border radius',
    type: 'number',
    group: 'panel',
    default: '4',
    description: 'Border radius of the results panel.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-shadow',
    label: 'Panel shadow',
    type: 'shadow',
    group: 'panel',
    default: [
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 1,
        color: '23, 23, 23',
        opacity: 0.05,
      },
      {
        offsetX: 0,
        offsetY: 6,
        blur: 16,
        spread: -4,
        color: '23, 23, 23',
        opacity: 0.15,
      },
    ],
    description: 'Box shadow of the results panel.',
  },
  {
    key: 'autocomplete-panel-border-opacity',
    label: 'Panel border opacity',
    type: 'number',
    group: 'panel',
    default: '0.2',
    description: 'Opacity of the panel border.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-panel-gap',
    label: 'Panel gap',
    type: 'number',
    group: 'panel',
    default: '8',
    description: 'Gap between sections in the panel.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-padding',
    label: 'Panel padding',
    type: 'number',
    group: 'panel',
    default: '8',
    description: 'Inner padding of the panel.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-panel-columns',
    label: 'Panel column sizes',
    type: 'text',
    group: 'panel',
    default: '1fr 1fr',
    description:
      'CSS grid column sizes for the two-column layout (e.g. "1fr 2fr", "300px 1fr").',
  },
  {
    key: 'autocomplete-panel-columns-breakpoint',
    label: 'Panel columns breakpoint',
    type: 'number',
    group: 'panel',
    default: '680',
    description:
      'Viewport width in pixels below which the two-column layout collapses to a single column.',
    constraints: { min: 0, max: 1920, step: 10, unit: 'px' },
  },

  // --- Items ---
  {
    key: 'autocomplete-item-icon-box-size',
    label: 'Item icon box size',
    type: 'number',
    group: 'items',
    default: '28',
    description:
      'Width and height of the icon container box inside result items.',
    constraints: { min: 16, max: 48, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-border-radius',
    label: 'Item border radius',
    type: 'number',
    group: 'items',
    default: '4',
    description: 'Border radius of result items.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-selected-opacity',
    label: 'Selected item opacity',
    type: 'number',
    group: 'items',
    default: '0.1',
    description: 'Background opacity of the selected/hovered item.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-item-min-height',
    label: 'Item min height',
    type: 'number',
    group: 'items',
    default: '40',
    description: 'Minimum height of each result item.',
    constraints: { min: 24, max: 64, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-padding',
    label: 'Item padding',
    type: 'number',
    group: 'items',
    default: '4',
    description: 'Inner padding of each result item.',
    constraints: { min: 0, max: 16, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-gap',
    label: 'Item gap',
    type: 'number',
    group: 'items',
    default: '8',
    description: 'Gap between icon and text within an item.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-item-line-height',
    label: 'Item line height',
    type: 'number',
    group: 'items',
    default: '1.25',
    description: 'Line height of item text.',
    constraints: { min: 1, max: 2.5, step: 0.05, unit: 'em' },
  },
  {
    key: 'autocomplete-item-icon-color',
    label: 'Item icon color',
    type: 'color',
    group: 'colors',
    default: '82, 82, 82',
    description: 'Color of icons inside result items.',
  },
  {
    key: 'autocomplete-item-action-color',
    label: 'Item action color',
    type: 'color',
    group: 'colors',
    default: '82, 82, 82',
    description: 'Color of action buttons inside result items.',
  },
  {
    key: 'autocomplete-highlight-weight',
    label: 'Highlight weight',
    type: 'number',
    group: 'items',
    default: '700',
    description: 'Font weight for highlighted/matched text.',
    constraints: { min: 100, max: 900, step: 100 },
  },

  // --- Headers ---
  {
    key: 'autocomplete-header-color',
    label: 'Header color',
    type: 'color',
    group: 'headers',
    default: { light: '30, 89, 255', dark: '110, 160, 255' },
    description: 'Color of section header text.',
  },
  {
    key: 'autocomplete-header-color-alpha',
    label: 'Header color alpha',
    type: 'number',
    group: 'headers',
    default: '1',
    description: 'Opacity of the section header text color.',
    constraints: { min: 0, max: 1 },
  },
  {
    key: 'autocomplete-header-font-size',
    label: 'Header font size',
    type: 'number',
    group: 'headers',
    default: '0.8',
    description: 'Font size of section headers.',
    constraints: { min: 0.5, max: 2, step: 0.1, unit: 'em' },
  },
  {
    key: 'autocomplete-header-font-weight',
    label: 'Header font weight',
    type: 'number',
    group: 'headers',
    default: '600',
    description: 'Font weight of section headers.',
    constraints: { min: 100, max: 900, step: 100 },
  },
  {
    key: 'autocomplete-header-margin-top',
    label: 'Header margin top',
    type: 'number',
    group: 'headers',
    default: '8',
    description: 'Space above section headers.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-header-margin-bottom',
    label: 'Header margin bottom',
    type: 'number',
    group: 'headers',
    default: '4',
    description: 'Space below section headers, before items.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-header-margin-left',
    label: 'Header margin left',
    type: 'number',
    group: 'headers',
    default: '4',
    description:
      'Left margin of section headers. Use to align with item content.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-header-margin-right',
    label: 'Header margin right',
    type: 'number',
    group: 'headers',
    default: '4',
    description: 'Right margin of section headers.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-header-text-transform',
    label: 'Header text transform',
    type: 'text',
    group: 'headers',
    default: 'uppercase',
    description:
      'Text transform for section headers (none, uppercase, lowercase, capitalize).',
  },
  {
    key: 'autocomplete-header-letter-spacing',
    label: 'Header letter spacing',
    type: 'number',
    group: 'headers',
    default: '0.05',
    description: 'Letter spacing for section headers.',
    constraints: { min: -0.05, max: 0.3, step: 0.01, unit: 'em' },
  },

  // --- No results ---
  {
    key: 'autocomplete-no-results-padding-y',
    label: 'No results vertical padding',
    type: 'number',
    group: 'noResults',
    default: '48',
    description: 'Vertical padding around the no results empty state.',
    constraints: { min: 0, max: 96, step: 4, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-padding-x',
    label: 'No results horizontal padding',
    type: 'number',
    group: 'noResults',
    default: '24',
    description: 'Horizontal padding around the no results empty state.',
    constraints: { min: 0, max: 96, step: 4, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-gap',
    label: 'No results gap',
    type: 'number',
    group: 'noResults',
    default: '12',
    description: 'Gap between elements in the no results state.',
    constraints: { min: 0, max: 48, step: 2, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-icon-color',
    label: 'No results icon color',
    type: 'color',
    group: 'noResults',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Color of the search icon in the no results state.',
  },
  {
    key: 'autocomplete-no-results-icon-opacity',
    label: 'No results icon opacity',
    type: 'number',
    group: 'noResults',
    default: '0.4',
    description: 'Opacity of the search icon in the no results state.',
    constraints: { min: 0, max: 1, step: 0.05 },
  },
  {
    key: 'autocomplete-no-results-icon-size',
    label: 'No results icon size',
    type: 'number',
    group: 'noResults',
    default: '24',
    description: 'Size of the search icon in the no results state.',
    constraints: { min: 12, max: 48, step: 2, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-icon-padding',
    label: 'No results icon padding',
    type: 'number',
    group: 'noResults',
    default: '6',
    description: 'Padding inside the icon circle in the no results state.',
    constraints: { min: 0, max: 24, step: 2, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-title-color',
    label: 'No results title color',
    type: 'color',
    group: 'noResults',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Color of the no results title text.',
  },
  {
    key: 'autocomplete-no-results-title-font-size',
    label: 'No results title font size',
    type: 'number',
    group: 'noResults',
    default: '18',
    description: 'Font size of the no results title.',
    constraints: { min: 12, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-title-font-weight',
    label: 'No results title font weight',
    type: 'number',
    group: 'noResults',
    default: '600',
    description: 'Font weight of the no results title.',
    constraints: { min: 100, max: 900, step: 100 },
  },
  {
    key: 'autocomplete-no-results-description-color',
    label: 'No results description color',
    type: 'color',
    group: 'noResults',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Color of the no results description text.',
  },
  {
    key: 'autocomplete-no-results-description-opacity',
    label: 'No results description opacity',
    type: 'number',
    group: 'noResults',
    default: '0.5',
    description: 'Opacity of the no results description text.',
    constraints: { min: 0, max: 1, step: 0.05 },
  },
  {
    key: 'autocomplete-no-results-description-font-size',
    label: 'No results description font size',
    type: 'number',
    group: 'noResults',
    default: '14',
    description: 'Font size of the no results description text.',
    constraints: { min: 10, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-color',
    label: 'No results clear button text color',
    type: 'color',
    group: 'noResults',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Text color of the clear query button.',
  },
  {
    key: 'autocomplete-no-results-clear-background-color',
    label: 'No results clear button background color',
    type: 'color',
    group: 'noResults',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Background color of the clear query button.',
  },
  {
    key: 'autocomplete-no-results-clear-background-opacity',
    label: 'No results clear button background opacity',
    type: 'number',
    group: 'noResults',
    default: '0.05',
    description: 'Background opacity of the clear query button.',
    constraints: { min: 0, max: 0.3, step: 0.01 },
  },
  {
    key: 'autocomplete-no-results-clear-border-color',
    label: 'No results clear button border color',
    type: 'color',
    group: 'noResults',
    default: { light: '38, 38, 38', dark: '255, 255, 255' },
    description: 'Border color of the clear query button.',
  },
  {
    key: 'autocomplete-no-results-clear-border-opacity',
    label: 'No results clear button border opacity',
    type: 'number',
    group: 'noResults',
    default: '0.15',
    description: 'Border opacity of the clear query button.',
    constraints: { min: 0, max: 1, step: 0.05 },
  },
  {
    key: 'autocomplete-no-results-clear-border-width',
    label: 'No results clear button border width',
    type: 'number',
    group: 'noResults',
    default: '1',
    description: 'Border width of the clear query button.',
    constraints: { min: 0, max: 4, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-font-size',
    label: 'No results clear button font size',
    type: 'number',
    group: 'noResults',
    default: '14',
    description: 'Font size of the clear query button.',
    constraints: { min: 10, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-font-weight',
    label: 'No results clear button font weight',
    type: 'number',
    group: 'noResults',
    default: '500',
    description: 'Font weight of the clear query button.',
    constraints: { min: 100, max: 900, step: 100 },
  },
  {
    key: 'autocomplete-no-results-clear-border-radius',
    label: 'No results clear button border radius',
    type: 'number',
    group: 'noResults',
    default: '6',
    description: 'Border radius of the clear query button.',
    constraints: { min: 0, max: 24, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-hover-border-opacity',
    label: 'No results clear button hover border opacity',
    type: 'number',
    group: 'noResults',
    default: '0.3',
    description: 'Border opacity of the clear query button on hover.',
    constraints: { min: 0, max: 1, step: 0.05 },
  },
  {
    key: 'autocomplete-no-results-clear-hover-background-opacity',
    label: 'No results clear button hover background opacity',
    type: 'number',
    group: 'noResults',
    default: '0.1',
    description: 'Background opacity of the clear query button on hover.',
    constraints: { min: 0, max: 0.5, step: 0.01 },
  },
  {
    key: 'autocomplete-no-results-clear-padding-y',
    label: 'No results clear button vertical padding',
    type: 'number',
    group: 'noResults',
    default: '8',
    description: 'Vertical padding inside the clear query button.',
    constraints: { min: 0, max: 24, step: 2, unit: 'px' },
  },
  {
    key: 'autocomplete-no-results-clear-padding-x',
    label: 'No results clear button horizontal padding',
    type: 'number',
    group: 'noResults',
    default: '20',
    description: 'Horizontal padding inside the clear query button.',
    constraints: { min: 0, max: 48, step: 2, unit: 'px' },
  },

  // --- Detached ---
  {
    key: 'autocomplete-detached-modal-max-width',
    label: 'Detached modal max width',
    type: 'number',
    group: 'detached',
    default: '680',
    description: 'Maximum width of the detached modal.',
    constraints: { min: 400, max: 1200, step: 10, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-max-height',
    label: 'Detached modal max height',
    type: 'number',
    group: 'detached',
    default: '500',
    description: 'Maximum height of the detached modal.',
    constraints: { min: 300, max: 1000, step: 10, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-border-radius',
    label: 'Detached modal border radius',
    type: 'number',
    group: 'detached',
    default: '8',
    description: 'Border radius of the detached modal.',
    constraints: { min: 0, max: 32, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-detached-modal-top',
    label: 'Detached modal top offset',
    type: 'number',
    group: 'detached',
    default: '3',
    description: 'Top offset of the detached modal from viewport.',
    constraints: { min: 0, max: 20, step: 1, unit: '%' },
  },
  {
    key: 'autocomplete-detached-modal-shadow',
    label: 'Detached modal shadow',
    type: 'shadow',
    group: 'detached',
    default: [
      {
        offsetX: 0,
        offsetY: 0,
        blur: 0,
        spread: 1,
        color: '23, 23, 23',
        opacity: 0.05,
      },
      {
        offsetX: 0,
        offsetY: 6,
        blur: 16,
        spread: -4,
        color: '23, 23, 23',
        opacity: 0.15,
      },
    ],
    description: 'Box shadow of the detached modal.',
  },
  {
    key: 'autocomplete-detached-form-border-opacity',
    label: 'Detached form border opacity',
    type: 'number',
    group: 'detached',
    default: '0.3',
    description: 'Opacity of the form border in detached mode.',
    constraints: { min: 0, max: 1 },
  },

  // --- Scrollbar ---
  {
    key: 'autocomplete-scrollbar-width',
    label: 'Scrollbar width',
    type: 'number',
    group: 'scrollbar',
    default: '6',
    description: 'Width of custom scrollbars in the panel.',
    constraints: { min: 2, max: 12, step: 1, unit: 'px' },
  },
  {
    key: 'autocomplete-scrollbar-color-mix',
    label: 'Scrollbar color mix',
    type: 'number',
    group: 'scrollbar',
    default: '40',
    description:
      'How much of the text color to mix into the scrollbar track color.',
    constraints: { min: 0, max: 100, step: 5, unit: '%' },
  },
];

export const autocompleteOverridesSchema = createThemeOverridesSchema(
  AUTOCOMPLETE_VARIABLES
);
